module.exports = [
"[project]/.next-internal/server/app/publications/page/actions.js [app-rsc] (server actions loader, ecmascript)", ((__turbopack_context__, module, exports) => {

}),
"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/not-found.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/components/publications-browser.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "PublicationsBrowser",
    ()=>PublicationsBrowser
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const PublicationsBrowser = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call PublicationsBrowser() from the server but PublicationsBrowser is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/publications-browser.tsx <module evaluation>", "PublicationsBrowser");
}),
"[project]/src/components/publications-browser.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "PublicationsBrowser",
    ()=>PublicationsBrowser
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const PublicationsBrowser = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call PublicationsBrowser() from the server but PublicationsBrowser is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/publications-browser.tsx", "PublicationsBrowser");
}),
"[project]/src/components/publications-browser.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$publications$2d$browser$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/publications-browser.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$publications$2d$browser$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/publications-browser.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$publications$2d$browser$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/components/page-hero.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "PageHero",
    ()=>PageHero
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
;
function PageHero({ title, subtitle }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
        className: "page-hero",
        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
            className: "container",
            children: [
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h1", {
                    children: title
                }, void 0, false, {
                    fileName: "[project]/src/components/page-hero.tsx",
                    lineNumber: 10,
                    columnNumber: 9
                }, this),
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                    children: subtitle
                }, void 0, false, {
                    fileName: "[project]/src/components/page-hero.tsx",
                    lineNumber: 11,
                    columnNumber: 9
                }, this)
            ]
        }, void 0, true, {
            fileName: "[project]/src/components/page-hero.tsx",
            lineNumber: 9,
            columnNumber: 7
        }, this)
    }, void 0, false, {
        fileName: "[project]/src/components/page-hero.tsx",
        lineNumber: 8,
        columnNumber: 5
    }, this);
}
}),
"[externals]/@prisma/client [external] (@prisma/client, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("@prisma/client", () => require("@prisma/client"));

module.exports = mod;
}),
"[project]/src/lib/prisma.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "prisma",
    ()=>prisma
]);
var __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2c$__cjs$29$__ = __turbopack_context__.i("[externals]/@prisma/client [external] (@prisma/client, cjs)");
;
const prisma = global.prisma ?? new __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2c$__cjs$29$__["PrismaClient"]({
    log: ("TURBOPACK compile-time truthy", 1) ? [
        "error",
        "warn"
    ] : "TURBOPACK unreachable"
});
if ("TURBOPACK compile-time truthy", 1) {
    global.prisma = prisma;
}
}),
"[project]/src/lib/mock-data.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "previewBlogs",
    ()=>previewBlogs,
    "previewMembers",
    ()=>previewMembers,
    "previewNews",
    ()=>previewNews,
    "previewProject",
    ()=>previewProject,
    "previewPublications",
    ()=>previewPublications
]);
const now = new Date("2026-03-15T00:00:00.000Z");
const previewNews = [
    {
        id: "preview-news-1",
        title: "Best Paper Award at AI Systems 2026",
        slug: "best-paper-award-ai-systems-2026",
        summary: "Our work on robust mobile sensing won the best paper award.",
        content: "Our latest paper presents a lightweight architecture for robust sensing in dynamic environments.",
        isPublished: true,
        publishedAt: new Date("2026-03-10T00:00:00.000Z"),
        createdAt: now,
        updatedAt: now
    },
    {
        id: "preview-news-2",
        title: "Two New PhD Students Joined the Lab",
        slug: "new-phd-students-2026",
        summary: "We are excited to welcome two new doctoral students this spring.",
        content: "The new members will work on human-centered AI and optimization systems.",
        isPublished: true,
        publishedAt: new Date("2026-03-01T00:00:00.000Z"),
        createdAt: now,
        updatedAt: now
    },
    {
        id: "preview-news-3",
        title: "Open-Source Toolkit Released",
        slug: "open-source-toolkit-release",
        summary: "We released our in-house experiment tracking toolkit as open-source.",
        content: "The toolkit helps teams run repeatable experiments across edge devices.",
        isPublished: true,
        publishedAt: new Date("2026-02-20T00:00:00.000Z"),
        createdAt: now,
        updatedAt: now
    }
];
const previewProject = {
    id: "preview-project-1",
    title: "Adaptive Mobility Intelligence",
    slug: "adaptive-mobility-intelligence",
    summary: "Real-time prediction and planning from urban sensor streams.",
    description: "This project explores a foundation-model-assisted pipeline for traffic forecasting, demand estimation, and safe route optimization.",
    linkUrl: "https://example.com/projects/adaptive-mobility-intelligence",
    isFeatured: true,
    createdAt: now,
    updatedAt: now
};
const previewMembers = [
    {
        id: "preview-member-1",
        name: "Dr. Akira Hasegawa",
        role: "Principal Investigator",
        bio: "Works on trustworthy AI systems for real-world sensing and decision-making.\n[RESEARCH_TOPIC]Foundation-model-driven ubiquitous intelligence",
        email: "hasegawa@example.com",
        websiteUrl: "https://example.com/akira",
        imageUrl: "/assets/logos/logo_light.png",
        order: 1,
        isActive: true,
        createdAt: now,
        updatedAt: now
    },
    {
        id: "preview-member-2",
        name: "Mina Sato",
        role: "PhD Student",
        bio: "Researches neural optimization in uncertain, dynamic environments.\n[RESEARCH_TOPIC]Neural optimization for adaptive sensing",
        email: "mina.sato@example.com",
        websiteUrl: null,
        imageUrl: null,
        order: 2,
        isActive: true,
        createdAt: now,
        updatedAt: now
    },
    {
        id: "preview-member-3",
        name: "Koji Tanaka",
        role: "Research Engineer",
        bio: "Builds production pipelines for edge ML experiments and model evaluation.\n[RESEARCH_TOPIC]Edge AI systems and evaluation pipelines",
        email: null,
        websiteUrl: "https://example.com/koji",
        imageUrl: null,
        order: 3,
        isActive: true,
        createdAt: now,
        updatedAt: now
    }
];
const previewPublications = [
    {
        id: "preview-pub-1",
        title: "Robust On-Device Representation Learning for Urban Mobility",
        authors: "A. Hasegawa, M. Sato, K. Tanaka",
        venue: "NeurIPS",
        year: 2025,
        url: "https://example.com/papers/robust-on-device-representation-learning",
        teaserImageUrl: "/assets/banners/banner_light.png",
        abstract: "We propose an on-device representation learning approach that remains stable under distribution shift.",
        createdAt: now,
        updatedAt: now
    },
    {
        id: "preview-pub-2",
        title: "Human-Centered Explanations for Multimodal Sensing Models",
        authors: "M. Sato, A. Hasegawa",
        venue: "CHI",
        year: 2024,
        url: "https://example.com/papers/human-centered-explanations",
        teaserImageUrl: null,
        abstract: "This paper studies explanation interfaces that improve operator trust and decision speed.",
        createdAt: now,
        updatedAt: now
    }
];
const previewBlogs = [
    {
        id: "preview-blog-1",
        title: "Designing Reliable Mobile AI Pipelines",
        slug: "designing-reliable-mobile-ai-pipelines",
        excerpt: "A practical checklist for robust data collection and evaluation on mobile devices.",
        markdown: `# Designing Reliable Mobile AI Pipelines

In this article, we share a practical checklist for deploying machine learning on mobile systems.

## Key Principles

- Treat data drift as a first-class production concern.
- Keep model monitoring close to the user context.
- Design fallback behavior before model rollout.

These principles improve both robustness and maintainability.`,
        isPublished: true,
        publishedAt: new Date("2026-03-05T00:00:00.000Z"),
        createdAt: now,
        updatedAt: now
    },
    {
        id: "preview-blog-2",
        title: "How We Evaluate Human-Centered AI",
        slug: "how-we-evaluate-human-centered-ai",
        excerpt: "Our internal rubric for measuring utility, transparency, and trust.",
        markdown: `# How We Evaluate Human-Centered AI

Evaluation should include both model metrics and user outcomes.

## Our Rubric

1. Task success and speed.
2. Comprehension of model behavior.
3. Confidence under uncertainty.

Balanced evaluation helps us ship systems that people can rely on.`,
        isPublished: true,
        publishedAt: new Date("2026-02-26T00:00:00.000Z"),
        createdAt: now,
        updatedAt: now
    }
];
}),
"[project]/src/lib/member-research-topic.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "buildMemberBio",
    ()=>buildMemberBio,
    "parseMemberBio",
    ()=>parseMemberBio
]);
const RESEARCH_TOPIC_MARKER = "[RESEARCH_TOPIC]";
function parseMemberBio(rawBio) {
    const normalizedBio = rawBio.trim();
    const markerMatch = normalizedBio.match(/(?:^|\n)\[RESEARCH_TOPIC\]([\s\S]*)$/);
    if (!markerMatch || typeof markerMatch.index !== "number") {
        return {
            bio: normalizedBio,
            researchTopic: ""
        };
    }
    const bio = normalizedBio.slice(0, markerMatch.index).trim();
    const researchTopic = markerMatch[1].trim();
    return {
        bio,
        researchTopic
    };
}
function buildMemberBio(bio, researchTopic) {
    const normalizedBio = bio.trim();
    const normalizedResearchTopic = researchTopic.trim();
    if (!normalizedResearchTopic) {
        return normalizedBio;
    }
    return `${normalizedBio}\n${RESEARCH_TOPIC_MARKER}${normalizedResearchTopic}`;
}
}),
"[project]/src/lib/members-remote-csv.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "getRemoteCsvMembers",
    ()=>getRemoteCsvMembers,
    "normalizeGoogleDriveImageUrl",
    ()=>normalizeGoogleDriveImageUrl
]);
const REQUIRED_HEADERS = [
    "name",
    "role"
];
const CANONICAL_HEADERS = new Set([
    "name",
    "role",
    "email",
    "homepage",
    "researchArea",
    "comment",
    "imageUrl",
    "graduateYear"
]);
const HEADER_ALIASES = {
    name: "name",
    名前: "name",
    氏名: "name",
    role: "role",
    position: "role",
    職位: "role",
    役職: "role",
    email: "email",
    mail: "email",
    メール: "email",
    メールアドレス: "email",
    homepage: "homepage",
    home: "homepage",
    website: "homepage",
    websiteurl: "homepage",
    personalpage: "homepage",
    ホームページ: "homepage",
    ウェブサイト: "homepage",
    researcharea: "researchArea",
    research: "researchArea",
    researchtopic: "researchArea",
    研究分野: "researchArea",
    研究領域: "researchArea",
    研究テーマ: "researchArea",
    comment: "comment",
    bio: "comment",
    備考: "comment",
    コメント: "comment",
    紹介: "comment",
    imageurl: "imageUrl",
    image: "imageUrl",
    photo: "imageUrl",
    photourl: "imageUrl",
    写真: "imageUrl",
    画像: "imageUrl",
    画像url: "imageUrl",
    写真url: "imageUrl",
    graduateyear: "graduateYear",
    graduationyear: "graduateYear",
    graduation: "graduateYear",
    gradyear: "graduateYear",
    卒業年: "graduateYear",
    修了年: "graduateYear"
};
function asOptionalString(value) {
    if (!value) {
        return null;
    }
    const normalized = value.trim();
    return normalized.length > 0 ? normalized : null;
}
function parseCsv(content) {
    const rows = [];
    let row = [];
    let field = "";
    let inQuotes = false;
    for(let i = 0; i < content.length; i += 1){
        const char = content[i];
        const next = content[i + 1];
        if (inQuotes) {
            if (char === '"' && next === '"') {
                field += '"';
                i += 1;
            } else if (char === '"') {
                inQuotes = false;
            } else {
                field += char;
            }
            continue;
        }
        if (char === '"') {
            inQuotes = true;
            continue;
        }
        if (char === ",") {
            row.push(field);
            field = "";
            continue;
        }
        if (char === "\n") {
            row.push(field);
            rows.push(row);
            row = [];
            field = "";
            continue;
        }
        if (char === "\r") {
            continue;
        }
        field += char;
    }
    if (field.length > 0 || row.length > 0) {
        row.push(field);
        rows.push(row);
    }
    return rows;
}
function fileIdFromGoogleDriveUrl(url) {
    if (!url.hostname.includes("drive.google.com")) {
        return null;
    }
    const match = url.pathname.match(/\/file\/d\/([^/]+)/);
    if (match?.[1]) {
        return match[1];
    }
    const openId = url.searchParams.get("id");
    return openId || null;
}
function normalizeGoogleDriveImageUrl(rawUrl) {
    if (!rawUrl) {
        return null;
    }
    const trimmed = rawUrl.trim();
    if (!trimmed) {
        return null;
    }
    // Treat common placeholder paths as "no image" to avoid noisy 404s like /default.png.
    if (/^(\/)?default\.png$/i.test(trimmed)) {
        return null;
    }
    try {
        const url = new URL(trimmed);
        const fileId = fileIdFromGoogleDriveUrl(url);
        if (!fileId) {
            return trimmed;
        }
        // Proxy via our app to avoid browser-side cross-origin and redirect-related image failures.
        return `/api/member-image?id=${encodeURIComponent(fileId)}`;
    } catch  {
        return trimmed;
    }
}
function normalizeGoogleCsvUrl(rawUrl) {
    try {
        const url = new URL(rawUrl);
        if (url.hostname.includes("docs.google.com") && url.pathname.includes("/spreadsheets/d/")) {
            const pathMatch = url.pathname.match(/^\/spreadsheets\/d\/([^/]+)/);
            if (!pathMatch?.[1]) {
                return rawUrl;
            }
            const hashGidMatch = url.hash.match(/gid=(\d+)/);
            const gid = url.searchParams.get("gid") || hashGidMatch?.[1] || "0";
            const csvUrl = new URL(url.toString());
            csvUrl.pathname = `/spreadsheets/d/${pathMatch[1]}/export`;
            csvUrl.search = "";
            csvUrl.searchParams.set("format", "csv");
            csvUrl.searchParams.set("gid", gid);
            csvUrl.hash = "";
            return csvUrl.toString();
        }
        const fileId = fileIdFromGoogleDriveUrl(url);
        if (fileId) {
            return `https://drive.google.com/uc?export=download&id=${fileId}`;
        }
    } catch  {
        return rawUrl;
    }
    return rawUrl;
}
function parseRevalidateSeconds(raw) {
    const parsed = Number(raw);
    if (!Number.isFinite(parsed) || parsed <= 0) {
        return 300;
    }
    return Math.floor(parsed);
}
function normalizeHeader(rawHeader) {
    return rawHeader.replace(/^\uFEFF/, "").trim().replace(/[^\p{L}\p{N}]+/gu, "").toLowerCase();
}
function toCanonicalHeader(rawHeader) {
    const normalized = normalizeHeader(rawHeader);
    const aliased = HEADER_ALIASES[normalized] ?? normalized;
    if (CANONICAL_HEADERS.has(aliased)) {
        return aliased;
    }
    if (normalized.includes("name")) {
        return "name";
    }
    if (normalized.includes("role") || normalized.includes("position")) {
        return "role";
    }
    if (normalized.includes("mail")) {
        return "email";
    }
    if (normalized.includes("home") || normalized.includes("website")) {
        return "homepage";
    }
    if (normalized.includes("research")) {
        return "researchArea";
    }
    if (normalized.includes("comment") || normalized.includes("bio")) {
        return "comment";
    }
    if (normalized.includes("image") || normalized.includes("photo")) {
        return "imageUrl";
    }
    if (normalized.includes("graduate") || normalized.includes("graduation") || normalized.includes("gradyear")) {
        return "graduateYear";
    }
    return null;
}
async function getRemoteCsvMembers() {
    const csvUrl = process.env.MEMBERS_SPREADSHEET_URL?.trim();
    if (!csvUrl) {
        return null;
    }
    const url = normalizeGoogleCsvUrl(csvUrl);
    const revalidateSeconds = parseRevalidateSeconds(process.env.MEMBERS_SPREADSHEET_REVALIDATE_SECONDS);
    const response = await fetch(url, {
        next: {
            revalidate: revalidateSeconds
        }
    });
    if (!response.ok) {
        throw new Error(`Failed to fetch members spreadsheet: ${response.status} ${response.statusText}`);
    }
    const csvText = await response.text();
    const records = parseCsv(csvText);
    if (records.length === 0) {
        return [];
    }
    let headerRowIndex = -1;
    let headers = [];
    for(let i = 0; i < records.length; i += 1){
        const candidateHeaders = records[i].map((value)=>toCanonicalHeader(value));
        const availableHeaders = candidateHeaders.filter((header)=>header !== null);
        const hasAllRequired = REQUIRED_HEADERS.every((required)=>availableHeaders.includes(required));
        if (hasAllRequired) {
            headerRowIndex = i;
            headers = candidateHeaders;
            break;
        }
    }
    if (headerRowIndex < 0) {
        throw new Error("Missing required members headers: name and/or role");
    }
    const parsed = [];
    for(let i = headerRowIndex + 1; i < records.length; i += 1){
        const values = new Map();
        const row = records[i];
        for(let j = 0; j < headers.length; j += 1){
            const header = headers[j];
            if (!header) {
                continue;
            }
            values.set(header, row[j] ?? "");
        }
        const name = asOptionalString(values.get("name"));
        const role = asOptionalString(values.get("role"));
        const email = asOptionalString(values.get("email"));
        const homepage = asOptionalString(values.get("homepage"));
        const researchArea = asOptionalString(values.get("researchArea"));
        const comment = asOptionalString(values.get("comment"));
        const imageUrl = normalizeGoogleDriveImageUrl(asOptionalString(values.get("imageUrl")));
        const graduateYear = asOptionalString(values.get("graduateYear"));
        if (!name && !role && !email && !homepage && !researchArea && !comment && !imageUrl && !graduateYear) {
            continue;
        }
        if (!name || !role) {
            console.warn(`Skipping members row ${i + 1}: name and role are required.`, JSON.stringify({
                name: values.get("name") ?? "",
                role: values.get("role") ?? ""
            }));
            continue;
        }
        parsed.push({
            id: `remote-member-${i}`,
            name,
            role,
            email,
            homepage,
            researchArea,
            comment,
            imageUrl,
            graduateYear
        });
    }
    return parsed;
}
}),
"[project]/src/lib/news-remote-csv.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "getRemoteCsvNews",
    ()=>getRemoteCsvNews
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$members$2d$remote$2d$csv$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/members-remote-csv.ts [app-rsc] (ecmascript)");
;
const REQUIRED_HEADERS = [
    "date",
    "title",
    "content"
];
const CANONICAL_HEADERS = new Set([
    "date",
    "title",
    "content",
    "type",
    "highlight",
    "imageUrl",
    "externalUrl"
]);
const HEADER_ALIASES = {
    date: "date",
    publishedat: "date",
    publisheddate: "date",
    datetime: "date",
    日付: "date",
    title: "title",
    タイトル: "title",
    content: "content",
    body: "content",
    本文: "content",
    内容: "content",
    type: "type",
    category: "type",
    種別: "type",
    区分: "type",
    highlight: "highlight",
    featured: "highlight",
    注目: "highlight",
    imageurl: "imageUrl",
    image: "imageUrl",
    photo: "imageUrl",
    画像: "imageUrl",
    画像url: "imageUrl",
    写真url: "imageUrl",
    externalurl: "externalUrl",
    link: "externalUrl",
    url: "externalUrl",
    参考url: "externalUrl",
    外部url: "externalUrl",
    外部リンク: "externalUrl"
};
function asOptionalString(value) {
    if (!value) {
        return null;
    }
    const normalized = value.trim();
    return normalized.length > 0 ? normalized : null;
}
function parseCsv(content) {
    const rows = [];
    let row = [];
    let field = "";
    let inQuotes = false;
    for(let i = 0; i < content.length; i += 1){
        const char = content[i];
        const next = content[i + 1];
        if (inQuotes) {
            if (char === '"' && next === '"') {
                field += '"';
                i += 1;
            } else if (char === '"') {
                inQuotes = false;
            } else {
                field += char;
            }
            continue;
        }
        if (char === '"') {
            inQuotes = true;
            continue;
        }
        if (char === ",") {
            row.push(field);
            field = "";
            continue;
        }
        if (char === "\n") {
            row.push(field);
            rows.push(row);
            row = [];
            field = "";
            continue;
        }
        if (char === "\r") {
            continue;
        }
        field += char;
    }
    if (field.length > 0 || row.length > 0) {
        row.push(field);
        rows.push(row);
    }
    return rows;
}
function fileIdFromGoogleDriveUrl(url) {
    if (!url.hostname.includes("drive.google.com")) {
        return null;
    }
    const match = url.pathname.match(/\/file\/d\/([^/]+)/);
    if (match?.[1]) {
        return match[1];
    }
    const openId = url.searchParams.get("id");
    return openId || null;
}
function normalizeGoogleCsvUrl(rawUrl) {
    try {
        const url = new URL(rawUrl);
        if (url.hostname.includes("docs.google.com") && url.pathname.includes("/spreadsheets/d/")) {
            const pathMatch = url.pathname.match(/^\/spreadsheets\/d\/([^/]+)/);
            if (!pathMatch?.[1]) {
                return rawUrl;
            }
            const hashGidMatch = url.hash.match(/gid=(\d+)/);
            const gid = url.searchParams.get("gid") || hashGidMatch?.[1] || "0";
            const csvUrl = new URL(url.toString());
            csvUrl.pathname = `/spreadsheets/d/${pathMatch[1]}/export`;
            csvUrl.search = "";
            csvUrl.searchParams.set("format", "csv");
            csvUrl.searchParams.set("gid", gid);
            csvUrl.hash = "";
            return csvUrl.toString();
        }
        const fileId = fileIdFromGoogleDriveUrl(url);
        if (fileId) {
            return `https://drive.google.com/uc?export=download&id=${fileId}`;
        }
    } catch  {
        return rawUrl;
    }
    return rawUrl;
}
function parseRevalidateSeconds(raw) {
    const parsed = Number(raw);
    if (!Number.isFinite(parsed) || parsed <= 0) {
        return 300;
    }
    return Math.floor(parsed);
}
function normalizeHeader(rawHeader) {
    return rawHeader.replace(/^\uFEFF/, "").trim().replace(/[^\p{L}\p{N}]+/gu, "").toLowerCase();
}
function toCanonicalHeader(rawHeader) {
    const normalized = normalizeHeader(rawHeader);
    const aliased = HEADER_ALIASES[normalized] ?? normalized;
    if (CANONICAL_HEADERS.has(aliased)) {
        return aliased;
    }
    if (normalized.includes("date")) {
        return "date";
    }
    if (normalized.includes("title")) {
        return "title";
    }
    if (normalized.includes("content") || normalized.includes("body")) {
        return "content";
    }
    if (normalized.includes("type") || normalized.includes("category")) {
        return "type";
    }
    if (normalized.includes("highlight") || normalized.includes("feature")) {
        return "highlight";
    }
    if (normalized.includes("image") || normalized.includes("photo")) {
        return "imageUrl";
    }
    if (normalized.includes("external") || normalized === "url" || normalized.includes("link")) {
        return "externalUrl";
    }
    return null;
}
function parseDateOrThrow(raw, rowNumber) {
    if (!raw) {
        throw new Error(`CSV row ${rowNumber} is invalid. date is required.`);
    }
    const parsed = new Date(raw);
    if (Number.isNaN(parsed.getTime())) {
        throw new Error(`CSV row ${rowNumber} has invalid date: ${raw}`);
    }
    return parsed;
}
async function getRemoteCsvNews() {
    const csvUrl = process.env.NEWS_SPREADSHEET_URL?.trim();
    if (!csvUrl) {
        return null;
    }
    const url = normalizeGoogleCsvUrl(csvUrl);
    const revalidateSeconds = parseRevalidateSeconds(process.env.NEWS_SPREADSHEET_REVALIDATE_SECONDS);
    const response = await fetch(url, {
        next: {
            revalidate: revalidateSeconds
        }
    });
    if (!response.ok) {
        throw new Error(`Failed to fetch news CSV: ${response.status} ${response.statusText}`);
    }
    const csvText = await response.text();
    const records = parseCsv(csvText);
    if (records.length === 0) {
        return [];
    }
    const headers = records[0].map((value)=>toCanonicalHeader(value));
    const availableHeaders = headers.filter((header)=>header !== null);
    for (const required of REQUIRED_HEADERS){
        if (!availableHeaders.includes(required)) {
            throw new Error(`Missing required CSV header: ${required}`);
        }
    }
    const parsed = [];
    for(let i = 1; i < records.length; i += 1){
        const values = new Map();
        const row = records[i];
        for(let j = 0; j < headers.length; j += 1){
            const header = headers[j];
            if (!header) {
                continue;
            }
            values.set(header, row[j] ?? "");
        }
        const title = asOptionalString(values.get("title"));
        const content = asOptionalString(values.get("content"));
        const dateValue = asOptionalString(values.get("date"));
        if (!title && !content && !dateValue) {
            continue;
        }
        if (!title || !content) {
            throw new Error(`CSV row ${i + 1} is invalid. title and content are required.`);
        }
        parsed.push({
            id: `remote-news-${i}`,
            publishedAt: parseDateOrThrow(dateValue, i + 1),
            title,
            content,
            type: asOptionalString(values.get("type")),
            highlight: asOptionalString(values.get("highlight")),
            imageUrl: (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$members$2d$remote$2d$csv$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["normalizeGoogleDriveImageUrl"])(asOptionalString(values.get("imageUrl"))),
            externalUrl: asOptionalString(values.get("externalUrl"))
        });
    }
    parsed.sort((a, b)=>b.publishedAt.getTime() - a.publishedAt.getTime());
    return parsed;
}
}),
"[project]/src/lib/publications-remote-csv.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "getRemoteCsvPublications",
    ()=>getRemoteCsvPublications
]);
const REQUIRED_HEADERS = [
    "title",
    "authors",
    "venue",
    "year"
];
const CANONICAL_HEADERS = new Set([
    "title",
    "authors",
    "venue",
    "year",
    "url",
    "projectUrl",
    "codeUrl",
    "teaserImageUrl",
    "abstract",
    "highlight",
    "feature"
]);
const HEADER_ALIASES = {
    title: "title",
    authors: "authors",
    venue: "venue",
    year: "year",
    url: "url",
    projecturl: "projectUrl",
    codeurl: "codeUrl",
    teaserimageurl: "teaserImageUrl",
    abstract: "abstract",
    highlight: "highlight",
    feature: "feature",
    featured: "feature",
    features: "feature",
    featureorder: "feature",
    feature_rank: "feature",
    featureorderrank: "feature",
    feature_order: "feature"
};
function asOptionalString(value) {
    if (!value) {
        return null;
    }
    const normalized = value.trim();
    return normalized.length > 0 ? normalized : null;
}
function parseCsv(content) {
    const rows = [];
    let row = [];
    let field = "";
    let inQuotes = false;
    for(let i = 0; i < content.length; i += 1){
        const char = content[i];
        const next = content[i + 1];
        if (inQuotes) {
            if (char === '"' && next === '"') {
                field += '"';
                i += 1;
            } else if (char === '"') {
                inQuotes = false;
            } else {
                field += char;
            }
            continue;
        }
        if (char === '"') {
            inQuotes = true;
            continue;
        }
        if (char === ",") {
            row.push(field);
            field = "";
            continue;
        }
        if (char === "\n") {
            row.push(field);
            rows.push(row);
            row = [];
            field = "";
            continue;
        }
        if (char === "\r") {
            continue;
        }
        field += char;
    }
    if (field.length > 0 || row.length > 0) {
        row.push(field);
        rows.push(row);
    }
    return rows;
}
function fileIdFromGoogleDriveUrl(url) {
    if (url.hostname.includes("drive.google.com")) {
        const match = url.pathname.match(/\/file\/d\/([^/]+)/);
        if (match?.[1]) {
            return match[1];
        }
        const openId = url.searchParams.get("id");
        if (openId) {
            return openId;
        }
    }
    return null;
}
function normalizeGoogleCsvUrl(rawUrl) {
    try {
        const url = new URL(rawUrl);
        if (url.hostname.includes("docs.google.com") && url.pathname.includes("/spreadsheets/d/")) {
            const pathMatch = url.pathname.match(/^\/spreadsheets\/d\/([^/]+)/);
            if (!pathMatch?.[1]) {
                return rawUrl;
            }
            const hashGidMatch = url.hash.match(/gid=(\d+)/);
            const gid = url.searchParams.get("gid") || hashGidMatch?.[1] || "0";
            const csvUrl = new URL(url.toString());
            csvUrl.pathname = `/spreadsheets/d/${pathMatch[1]}/gviz/tq`;
            csvUrl.search = "";
            csvUrl.searchParams.set("tqx", "out:csv");
            csvUrl.searchParams.set("gid", gid);
            csvUrl.hash = "";
            return csvUrl.toString();
        }
        const fileId = fileIdFromGoogleDriveUrl(url);
        if (fileId) {
            return `https://drive.google.com/uc?export=download&id=${fileId}`;
        }
    } catch  {
        return rawUrl;
    }
    return rawUrl;
}
function parseRevalidateSeconds(raw) {
    const parsed = Number(raw);
    if (!Number.isFinite(parsed) || parsed <= 0) {
        return 300;
    }
    return Math.floor(parsed);
}
function normalizeHeader(rawHeader) {
    return rawHeader.replace(/^\uFEFF/, "").trim().replace(/\s+/g, "").toLowerCase();
}
function toCanonicalHeader(rawHeader) {
    const normalized = normalizeHeader(rawHeader);
    const aliased = HEADER_ALIASES[normalized] ?? normalized;
    if (CANONICAL_HEADERS.has(aliased)) {
        return aliased;
    }
    return null;
}
function parseOptionalPositiveInteger(raw, fieldName, rowNumber) {
    const value = asOptionalString(raw);
    if (!value) {
        return null;
    }
    const parsed = Number(value);
    const normalized = Math.trunc(parsed);
    const isIntegerLike = Number.isFinite(parsed) && Math.abs(parsed - normalized) < Number.EPSILON;
    if (!isIntegerLike || !Number.isSafeInteger(normalized) || normalized <= 0) {
        throw new Error(`CSV row ${rowNumber} has invalid ${fieldName}: ${value}`);
    }
    return normalized;
}
async function getRemoteCsvPublications() {
    const csvUrl = process.env.PUBLICATIONS_CSV_URL?.trim();
    if (!csvUrl) {
        return null;
    }
    const url = normalizeGoogleCsvUrl(csvUrl);
    const revalidateSeconds = parseRevalidateSeconds(process.env.PUBLICATIONS_CSV_REVALIDATE_SECONDS);
    const response = await fetch(url, {
        next: {
            revalidate: revalidateSeconds
        }
    });
    if (!response.ok) {
        throw new Error(`Failed to fetch publication CSV: ${response.status} ${response.statusText}`);
    }
    const csvText = await response.text();
    const records = parseCsv(csvText);
    if (records.length === 0) {
        return [];
    }
    const headers = records[0].map((value)=>toCanonicalHeader(value));
    const availableHeaders = headers.filter((header)=>header !== null);
    for (const required of REQUIRED_HEADERS){
        if (!availableHeaders.includes(required)) {
            throw new Error(`Missing required CSV header: ${required}`);
        }
    }
    const parsed = [];
    for(let i = 1; i < records.length; i += 1){
        const values = new Map();
        const row = records[i];
        for(let j = 0; j < headers.length; j += 1){
            const header = headers[j];
            if (!header) {
                continue;
            }
            values.set(header, row[j] ?? "");
        }
        const title = asOptionalString(values.get("title"));
        const authors = asOptionalString(values.get("authors"));
        const venue = asOptionalString(values.get("venue"));
        const yearRaw = asOptionalString(values.get("year"));
        if (!title && !authors && !venue && !yearRaw) {
            continue;
        }
        if (!title || !authors || !venue || !yearRaw) {
            throw new Error(`CSV row ${i + 1} is invalid. title, authors, venue, and year are required.`);
        }
        const year = Number(yearRaw);
        if (!Number.isFinite(year) || !Number.isInteger(year)) {
            throw new Error(`CSV row ${i + 1} has invalid year: ${yearRaw}`);
        }
        parsed.push({
            id: `remote-csv-${i}`,
            title,
            authors,
            venue,
            year,
            url: asOptionalString(values.get("url")),
            projectUrl: asOptionalString(values.get("projectUrl")),
            codeUrl: asOptionalString(values.get("codeUrl")),
            teaserImageUrl: asOptionalString(values.get("teaserImageUrl")),
            abstract: asOptionalString(values.get("abstract")),
            highlight: asOptionalString(values.get("highlight")),
            feature: parseOptionalPositiveInteger(values.get("feature"), "feature", i + 1)
        });
    }
    parsed.sort((a, b)=>b.year - a.year);
    return parsed;
}
}),
"[project]/src/lib/data.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "getBlogBySlug",
    ()=>getBlogBySlug,
    "getBlogs",
    ()=>getBlogs,
    "getFeaturedProject",
    ()=>getFeaturedProject,
    "getFeaturedPublications",
    ()=>getFeaturedPublications,
    "getLatestNews",
    ()=>getLatestNews,
    "getMembers",
    ()=>getMembers,
    "getNews",
    ()=>getNews,
    "getPublications",
    ()=>getPublications
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/prisma.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$mock$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/mock-data.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$member$2d$research$2d$topic$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/member-research-topic.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$members$2d$remote$2d$csv$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/members-remote-csv.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$news$2d$remote$2d$csv$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/news-remote-csv.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$publications$2d$remote$2d$csv$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/publications-remote-csv.ts [app-rsc] (ecmascript)");
;
;
;
;
;
;
function isDesignPreviewEnabled() {
    return process.env.DESIGN_PREVIEW === "1" || process.env.DESIGN_PREVIEW === "true";
}
async function getLatestNews(limit = 3) {
    const normalizedLimit = Math.max(0, limit);
    if (normalizedLimit === 0) {
        return [];
    }
    if (isDesignPreviewEnabled()) {
        return __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$mock$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["previewNews"].slice(0, normalizedLimit).map(toPublicNewsFromDbRecord);
    }
    const remoteCsvNews = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$news$2d$remote$2d$csv$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getRemoteCsvNews"])().catch((error)=>{
        console.error("Failed to load remote news spreadsheet.", error);
        return null;
    });
    if (remoteCsvNews) {
        return remoteCsvNews.slice(0, normalizedLimit).map((item)=>({
                id: item.id,
                title: item.title,
                slug: null,
                summary: summarizeNewsContent(item.content),
                content: item.content,
                publishedAt: item.publishedAt,
                type: item.type,
                highlight: item.highlight,
                imageUrl: item.imageUrl,
                externalUrl: item.externalUrl
            }));
    }
    const news = await __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].news.findMany({
        where: {
            isPublished: true
        },
        orderBy: {
            publishedAt: "desc"
        },
        take: normalizedLimit
    });
    return news.map(toPublicNewsFromDbRecord);
}
async function getNews() {
    if (isDesignPreviewEnabled()) {
        return __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$mock$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["previewNews"].map(toPublicNewsFromDbRecord);
    }
    const remoteCsvNews = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$news$2d$remote$2d$csv$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getRemoteCsvNews"])().catch((error)=>{
        console.error("Failed to load remote news spreadsheet.", error);
        return null;
    });
    if (remoteCsvNews) {
        return remoteCsvNews.map((item)=>({
                id: item.id,
                title: item.title,
                slug: null,
                summary: summarizeNewsContent(item.content),
                content: item.content,
                publishedAt: item.publishedAt,
                type: item.type,
                highlight: item.highlight,
                imageUrl: item.imageUrl,
                externalUrl: item.externalUrl
            }));
    }
    const news = await __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].news.findMany({
        where: {
            isPublished: true
        },
        orderBy: {
            publishedAt: "desc"
        }
    });
    return news.map(toPublicNewsFromDbRecord);
}
async function getFeaturedProject() {
    if (isDesignPreviewEnabled()) {
        return __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$mock$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["previewProject"];
    }
    const featured = await __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].project.findFirst({
        where: {
            isFeatured: true
        },
        orderBy: {
            updatedAt: "desc"
        }
    });
    if (featured) {
        return featured;
    }
    return __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].project.findFirst({
        orderBy: {
            updatedAt: "desc"
        }
    });
}
async function getMembers() {
    if (isDesignPreviewEnabled()) {
        return __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$mock$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["previewMembers"].map((member)=>{
            const { bio, researchTopic } = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$member$2d$research$2d$topic$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["parseMemberBio"])(member.bio);
            return {
                id: member.id,
                name: member.name,
                role: member.role,
                email: member.email,
                websiteUrl: member.websiteUrl,
                imageUrl: (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$members$2d$remote$2d$csv$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["normalizeGoogleDriveImageUrl"])(member.imageUrl),
                researchArea: researchTopic || null,
                comment: bio || null,
                graduateYear: null
            };
        });
    }
    const remoteCsvMembers = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$members$2d$remote$2d$csv$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getRemoteCsvMembers"])().catch((error)=>{
        console.error("Failed to load remote members spreadsheet.", error);
        return null;
    });
    if (remoteCsvMembers) {
        return remoteCsvMembers.map((member)=>({
                id: member.id,
                name: member.name,
                role: member.role,
                email: member.email,
                websiteUrl: member.homepage,
                imageUrl: (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$members$2d$remote$2d$csv$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["normalizeGoogleDriveImageUrl"])(member.imageUrl),
                researchArea: member.researchArea,
                comment: member.comment,
                graduateYear: member.graduateYear
            }));
    }
    const dbMembers = await __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].member.findMany({
        where: {
            isActive: true
        },
        orderBy: [
            {
                order: "asc"
            },
            {
                createdAt: "asc"
            }
        ]
    });
    return dbMembers.map((member)=>{
        const { bio, researchTopic } = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$member$2d$research$2d$topic$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["parseMemberBio"])(member.bio);
        return {
            id: member.id,
            name: member.name,
            role: member.role,
            email: member.email,
            websiteUrl: member.websiteUrl,
            imageUrl: (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$members$2d$remote$2d$csv$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["normalizeGoogleDriveImageUrl"])(member.imageUrl),
            researchArea: researchTopic || null,
            comment: bio || null,
            graduateYear: null
        };
    });
}
async function getPublications() {
    if (isDesignPreviewEnabled()) {
        return __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$mock$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["previewPublications"];
    }
    const remoteCsvPublications = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$publications$2d$remote$2d$csv$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getRemoteCsvPublications"])().catch((error)=>{
        console.error("Failed to load remote publication CSV.", error);
        return null;
    });
    if (remoteCsvPublications) {
        return remoteCsvPublications;
    }
    return __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].publication.findMany({
        orderBy: [
            {
                year: "desc"
            },
            {
                createdAt: "desc"
            }
        ]
    });
}
function parseFeatureRank(value) {
    if (typeof value === "number" && Number.isSafeInteger(value) && value > 0) {
        return value;
    }
    if (typeof value === "string") {
        const trimmed = value.trim();
        if (!/^\d+$/.test(trimmed)) {
            return null;
        }
        const parsed = Number(trimmed);
        if (Number.isSafeInteger(parsed) && parsed > 0) {
            return parsed;
        }
    }
    return null;
}
function getFeaturedPublications(publications, limit = 3) {
    if (limit <= 0 || publications.length === 0) {
        return [];
    }
    const ranked = publications.map((publication, index)=>({
            publication,
            index,
            rank: parseFeatureRank(publication.feature)
        })).filter((entry)=>entry.rank !== null).sort((left, right)=>{
        if (left.rank !== right.rank) {
            return left.rank - right.rank;
        }
        return left.index - right.index;
    }).slice(0, limit).map((entry)=>entry.publication);
    if (ranked.length >= limit) {
        return ranked;
    }
    const selectedIds = new Set(ranked.map((publication)=>publication.id));
    const fallback = publications.filter((publication)=>!selectedIds.has(publication.id)).slice(0, limit - ranked.length);
    return [
        ...ranked,
        ...fallback
    ];
}
async function getBlogs() {
    if (isDesignPreviewEnabled()) {
        return __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$mock$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["previewBlogs"];
    }
    return __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].blogPost.findMany({
        where: {
            isPublished: true
        },
        orderBy: {
            publishedAt: "desc"
        }
    });
}
async function getBlogBySlug(slug) {
    if (isDesignPreviewEnabled()) {
        return __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$mock$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["previewBlogs"].find((post)=>post.slug === slug) ?? null;
    }
    return __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].blogPost.findFirst({
        where: {
            slug,
            isPublished: true
        }
    });
}
function summarizeNewsContent(content, maxLength = 180) {
    const compact = content.replace(/\s+/g, " ").trim();
    if (compact.length <= maxLength) {
        return compact;
    }
    return `${compact.slice(0, maxLength - 1)}…`;
}
function toPublicNewsFromDbRecord(item) {
    return {
        id: item.id,
        title: item.title,
        slug: item.slug,
        summary: item.summary,
        content: item.content,
        publishedAt: item.publishedAt,
        type: null,
        highlight: null,
        imageUrl: null,
        externalUrl: null
    };
}
}),
"[project]/src/app/publications/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>PublicationsPage,
    "generateMetadata",
    ()=>generateMetadata
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$publications$2d$browser$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/publications-browser.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$page$2d$hero$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/page-hero.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/data.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$messages$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/i18n/messages/index.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$request$2d$locale$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/i18n/request-locale.ts [app-rsc] (ecmascript)");
;
;
;
;
;
;
async function generateMetadata() {
    const locale = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$request$2d$locale$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["resolveRequestLocale"])();
    const messages = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$messages$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getMessages"])(locale);
    return {
        title: messages.publications.title,
        description: messages.publications.subtitle
    };
}
async function PublicationsPage() {
    const locale = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$request$2d$locale$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["resolveRequestLocale"])();
    const messages = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$messages$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getMessages"])(locale);
    const publications = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getPublications"])();
    const publicationItems = publications.map((item)=>({
            id: item.id,
            title: item.title,
            authors: item.authors,
            venue: item.venue,
            year: item.year,
            url: item.url ?? null,
            projectUrl: item.projectUrl ?? null,
            codeUrl: item.codeUrl ?? null,
            teaserImageUrl: item.teaserImageUrl ?? null,
            abstract: item.abstract ?? null,
            highlight: item.highlight ?? null
        }));
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["Fragment"], {
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$page$2d$hero$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["PageHero"], {
                title: messages.publications.title,
                subtitle: messages.publications.subtitle
            }, void 0, false, {
                fileName: "[project]/src/app/publications/page.tsx",
                lineNumber: 38,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
                className: "section",
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                    className: "container list",
                    children: publications.length === 0 ? /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("article", {
                        className: "card",
                        children: [
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h2", {
                                children: messages.publications.noItemsTitle
                            }, void 0, false, {
                                fileName: "[project]/src/app/publications/page.tsx",
                                lineNumber: 44,
                                columnNumber: 15
                            }, this),
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                className: "muted",
                                children: messages.publications.noItemsBody
                            }, void 0, false, {
                                fileName: "[project]/src/app/publications/page.tsx",
                                lineNumber: 45,
                                columnNumber: 15
                            }, this)
                        ]
                    }, void 0, true, {
                        fileName: "[project]/src/app/publications/page.tsx",
                        lineNumber: 43,
                        columnNumber: 13
                    }, this) : /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$publications$2d$browser$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["PublicationsBrowser"], {
                        items: publicationItems,
                        messages: {
                            searchLabel: messages.publications.searchLabel,
                            searchPlaceholder: messages.publications.searchPlaceholder,
                            yearFilterLabel: messages.publications.yearFilterLabel,
                            allYears: messages.publications.allYears,
                            sortLabel: messages.publications.sortLabel,
                            sortNewest: messages.publications.sortNewest,
                            sortOldest: messages.publications.sortOldest,
                            sortTitleAsc: messages.publications.sortTitleAsc,
                            sortTitleDesc: messages.publications.sortTitleDesc,
                            pageLabel: messages.publications.pageLabel,
                            previousPage: messages.publications.previousPage,
                            nextPage: messages.publications.nextPage,
                            pageSummary: messages.publications.pageSummary,
                            noResultsTitle: messages.publications.noResultsTitle,
                            noResultsBody: messages.publications.noResultsBody,
                            clearFilters: messages.publications.clearFilters,
                            teaserAltSuffix: messages.publications.teaserAltSuffix,
                            paperAriaLabel: messages.publications.paperAriaLabel,
                            projectAriaLabel: messages.publications.projectAriaLabel,
                            codeAriaLabel: messages.publications.codeAriaLabel
                        }
                    }, void 0, false, {
                        fileName: "[project]/src/app/publications/page.tsx",
                        lineNumber: 48,
                        columnNumber: 13
                    }, this)
                }, void 0, false, {
                    fileName: "[project]/src/app/publications/page.tsx",
                    lineNumber: 41,
                    columnNumber: 9
                }, this)
            }, void 0, false, {
                fileName: "[project]/src/app/publications/page.tsx",
                lineNumber: 40,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true);
}
}),
"[project]/src/app/publications/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/publications/page.tsx [app-rsc] (ecmascript)"));
}),
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__bceb92cd._.js.map