module.exports = [
"[project]/src/components/site-footer.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "SiteFooter",
    ()=>SiteFooter
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
;
function SiteFooter({ messages }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("footer", {
        className: "site-footer",
        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
            className: "container footer-inner",
            children: [
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                    children: [
                        "© ",
                        new Date().getFullYear(),
                        " ",
                        messages.copyright
                    ]
                }, void 0, true, {
                    fileName: "[project]/src/components/site-footer.tsx",
                    lineNumber: 11,
                    columnNumber: 9
                }, this),
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("img", {
                    src: "/assets/logos/university_of_fukui_logo.svg",
                    alt: "University of Fukui",
                    className: "footer-logo"
                }, void 0, false, {
                    fileName: "[project]/src/components/site-footer.tsx",
                    lineNumber: 14,
                    columnNumber: 9
                }, this)
            ]
        }, void 0, true, {
            fileName: "[project]/src/components/site-footer.tsx",
            lineNumber: 10,
            columnNumber: 7
        }, this)
    }, void 0, false, {
        fileName: "[project]/src/components/site-footer.tsx",
        lineNumber: 9,
        columnNumber: 5
    }, this);
}
}),
"[project]/src/components/site-header.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "SiteHeader",
    ()=>SiteHeader
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const SiteHeader = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call SiteHeader() from the server but SiteHeader is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/site-header.tsx <module evaluation>", "SiteHeader");
}),
"[project]/src/components/site-header.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "SiteHeader",
    ()=>SiteHeader
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const SiteHeader = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call SiteHeader() from the server but SiteHeader is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/site-header.tsx", "SiteHeader");
}),
"[project]/src/components/site-header.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$site$2d$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/site-header.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$site$2d$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/site-header.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$site$2d$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/lib/i18n/config.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "DEFAULT_LOCALE",
    ()=>DEFAULT_LOCALE,
    "LOCALE_COOKIE_NAME",
    ()=>LOCALE_COOKIE_NAME,
    "SUPPORTED_LOCALES",
    ()=>SUPPORTED_LOCALES,
    "isLocale",
    ()=>isLocale,
    "resolvePreferredLocale",
    ()=>resolvePreferredLocale
]);
const SUPPORTED_LOCALES = [
    "en",
    "ja",
    "zh"
];
const DEFAULT_LOCALE = "en";
const LOCALE_COOKIE_NAME = "site_locale";
function isLocale(value) {
    return value != null && SUPPORTED_LOCALES.includes(value);
}
function mapLanguageTagToLocale(tag) {
    const normalized = tag.toLowerCase();
    if (normalized.startsWith("ja")) {
        return "ja";
    }
    if (normalized.startsWith("zh")) {
        return "zh";
    }
    if (normalized.startsWith("en")) {
        return "en";
    }
    return null;
}
function resolvePreferredLocale(acceptLanguageHeader) {
    if (!acceptLanguageHeader) {
        return DEFAULT_LOCALE;
    }
    const tags = acceptLanguageHeader.split(",").map((part)=>part.split(";")[0]?.trim()).filter((part)=>Boolean(part));
    for (const tag of tags){
        const mapped = mapLanguageTagToLocale(tag);
        if (mapped) {
            return mapped;
        }
    }
    return DEFAULT_LOCALE;
}
}),
"[project]/src/lib/i18n/messages/en.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "enMessages",
    ()=>enMessages
]);
const enMessages = {
    metadata: {
        siteTitle: "Hasegawa Laboratory",
        siteDescription: "Laboratory homepage with research, publications, members, and admin-managed updates."
    },
    header: {
        brandTitle: "Hasegawa Laboratory",
        brandSubtitle: "Building Ubiquitous Intelligence.",
        mainNavAria: "Main Navigation",
        languageLabel: "Language",
        languages: {
            en: "EN",
            ja: "日本語",
            zh: "中文"
        },
        nav: {
            home: "Home",
            research: "Research",
            news: "News",
            blogs: "Blogs",
            publications: "Publications",
            members: "Members",
            joinUs: "Join Us",
            business: "Business",
            contact: "Contact"
        }
    },
    footer: {
        copyright: "Hasegawa Laboratory, University of Fukui."
    },
    notFound: {
        title: "Page not found",
        description: "The requested page does not exist.",
        cta: "Return to homepage"
    },
    home: {
        badge: "Hasegawa Laboratory",
        title: "Bridging Ubiquity and Intelligence",
        intro: "Our mission is to create intelligent systems that connect people, devices, and knowledge through mobile sensing and deep learning.",
        primaryCta: "Apply to Join Us",
        secondaryCta: "Explore Research",
        aboutTitle: "About",
        aboutBody: "HaseLab conducts research centered on ubiquitous artificial intelligence. We explore how to leverage the capabilities of foundation models, develop new generations of neural architectures, and deepen our understanding of the mechanisms underlying neural networks.",
        aboutCta: "See research domains",
        latestNewsTitle: "Latest News",
        noNewsTitle: "No news yet",
        noNewsBody: "News items will appear here after you add them from the admin dashboard.",
        viewAllNews: "View all news",
        latestProjectTitle: "Latest Project",
        featuredPublicationsTitle: "Featured Publications",
        viewAllPublications: "View all publications",
        visitProject: "Visit project page",
        noProject: "Add a project from the admin panel to highlight it here.",
        contactTitle: "Contact",
        quickInquiryTitle: "Quick Inquiry",
        quickInquiryBody: "Tell us your background, research interests, and preferred start timing. We usually respond within a few business days.",
        generalInfoTitle: "General Information",
        viewContactDetails: "View full contact details",
        sendEmailCta: "Email us now",
        labels: {
            email: "Email",
            address: "Address"
        }
    },
    research: {
        title: "Research",
        subtitle: "What we work on, what outcomes we produce, and where new students can contribute.",
        vision: {
            missionTitle: "Research Vision",
            missionStatement: "We build ubiquitous intelligence systems that are scientifically rigorous, practically deployable, and human-centered.",
            focusQuestionsTitle: "Current Focus Questions",
            focusQuestions: [
                "What data is missing for achieving artificial general intelligence?",
                "How can task-specific models be built from foundation models?",
                "Can an ensemble of small models rival a single large model?",
                "What kind of world models do foundation models acquire?",
                "How can highly reliable discriminative models be constructed?"
            ],
            imageAlt: "Students discussing experiment results in front of a dashboard",
            imageCaption: "A typical research cycle in our lab: problem framing, iterative experimentation, and weekly evidence-based reviews."
        },
        themesTitle: "Research Themes",
        themes: [
            {
                title: "Human Activity Recognition",
                description: "Recognising human activities with wearable sensors, deep learning-based signal processing, and rigorous time-series modelling.",
                whyItMatters: "Collecting and understanding human activities are essential for advancing healthcare monitoring, rehabilitation, sports performance analysis, and ambient assisted living.",
                methods: "Deep learning on time-series data, Time-series modelling, Wearable sensor fusion and signal preprocessing",
                outputs: "Establishing novel methods that transfer across domains, Constructing comprehensive benchmarks for human activity recognition, Published more than 30 peer-reviewed papers on this topic",
                imageSrc: "/assets/banners/har_banner.png",
                imageAlt: "Human Activity Recognition research banner",
                imagePosition: "left"
            },
            {
                title: "Ensemble Learning",
                description: "Exploring the potential of intelligent information processing through collections of small-scale models, rather than a single large-scale model.",
                whyItMatters: "Today's intelligent information processing driven by a single large-scale model is far removed from the process by which humans acquire collective intelligence.",
                methods: "Deep Ensemble Learning, Collaborative learning, Multi-agent Systems",
                outputs: "Establishing dynamic equilibrium learning in deep ensemble learning, Accelerating parallel learning in deep ensemble learning, Published more than 10 peer-reviewed papers on this topic",
                imageSrc: "/assets/banners/ensemble_banner.png",
                imageAlt: "Ensemble Learning research banner"
            },
            {
                title: "Visual Understanding",
                description: "Understanding what is happening in images and videos in the same way humans do.",
                whyItMatters: "It serves as a foundational technology to replace humans across diverse industrial settings, including autonomous driving and robotics.",
                methods: "Fine-grained visual recognition, Visual representation learning, Visual anomaly detection",
                outputs: "Achieving state-of-the-art performance in animal species classification and fine-grained categorisation, Establishing a mechanism for acquiring useful visual representations based on self-supervised learning, Published more than 20 peer-reviewed papers, including top international conference publications",
                imageSrc: "/assets/banners/visual_banner.png",
                imageAlt: "Visual Understanding research banner"
            },
            {
                title: "Foundation Models",
                description: "Investigating adaptation, compositionality, and world knowledge in large pre-trained models.",
                whyItMatters: "Foundation models define the core capabilities that many downstream AI systems depend on.",
                methods: "Parameter-efficient adaptation, instruction tuning, and probing of internal world models.",
                outputs: "Model adaptation frameworks, analysis toolchains, and comparative large-model studies.",
                imageSrc: "/assets/banners/foundation_banner.png",
                imageAlt: "Foundation Models research banner",
                imagePosition: "left"
            }
        ],
        themeLabels: {
            whyItMatters: "Why it matters",
            methods: "Methods and tools",
            outputs: "Research contributions",
            imagePlaceholder: "Image"
        },
        projectLabels: {
            problem: "Problem",
            approach: "Approach",
            status: "Status"
        },
        projectsTitle: "Active Projects",
        projects: [
            {
                title: "Adaptive Learning from Noisy Mobile Sensing",
                problem: "Mobile sensing data quality shifts across users, devices, and contexts.",
                approach: "Train robust feature extractors with confidence-aware data selection and online recalibration.",
                status: "Running",
                paperUrl: "/publications",
                codeUrl: "https://github.com",
                demoUrl: "/blogs"
            },
            {
                title: "Safe Decision Optimization for Dynamic Environments",
                problem: "Policies can fail when constraints and operating conditions change unexpectedly.",
                approach: "Combine predictive planning with constraint-aware optimization and stress-test simulations.",
                status: "Running",
                paperUrl: "/publications",
                demoUrl: "/news"
            },
            {
                title: "Explainable AI Co-Pilot for Domain Experts",
                problem: "Experts need actionable explanations, not only model scores.",
                approach: "Build an interactive explanation interface with iterative feedback loops and error analysis.",
                status: "Published",
                paperUrl: "/publications",
                demoUrl: "/blogs"
            },
            {
                title: "Resilient Edge-Cloud Infrastructure for Ubiquitous AI",
                problem: "Inference pipelines degrade under network disruption and partial hardware failures.",
                approach: "Design fallback scheduling and service recovery strategies validated on a digital-twin testbed.",
                status: "Idea",
                demoUrl: "/news"
            }
        ],
        projectLinks: {
            paper: "Paper",
            code: "Code",
            demo: "Demo"
        },
        outcomesTitle: "Results and Impact",
        outcomesSubtitle: "Representative outcomes from publication, deployment, and collaboration activities.",
        outcomes: [
            {
                title: "Top Publications",
                description: "Recent peer-reviewed papers in machine learning, optimization, and ubiquitous systems."
            },
            {
                title: "Awards and Recognition",
                description: "Student paper awards, competitive grants, and invited talks with international partners."
            },
            {
                title: "Deployments and Collaborations",
                description: "Joint projects with academic and industry collaborators targeting real-world operations."
            }
        ],
        byNumbersTitle: "By the Numbers",
        byNumbers: [
            {
                value: "12+",
                label: "papers in the last year"
            },
            {
                value: "6",
                label: "active collaborative projects"
            },
            {
                value: "4",
                label: "open-source research repositories"
            },
            {
                value: "15+",
                label: "student theses supervised"
            }
        ],
        joinByTopicTitle: "How Students Can Join by Topic",
        joinByTopic: [
            {
                theme: "Machine Learning & Data Intelligence",
                skillsTitle: "Helpful skills",
                skills: [
                    "Python",
                    "PyTorch",
                    "data preprocessing",
                    "experiment tracking"
                ],
                firstProjectTitle: "Good first project",
                firstProjectIdea: "Reproduce a baseline model, then improve robustness under synthetic sensor noise.",
                weeklyWorkflowTitle: "Typical weekly workflow",
                weeklyWorkflow: [
                    "paper reading",
                    "coding",
                    "experiment runs",
                    "weekly review meeting"
                ]
            },
            {
                theme: "Optimization & Decision Systems",
                skillsTitle: "Helpful skills",
                skills: [
                    "linear algebra",
                    "optimization",
                    "simulation",
                    "algorithm design"
                ],
                firstProjectTitle: "Good first project",
                firstProjectIdea: "Implement a constrained planning baseline and compare performance under disturbances.",
                weeklyWorkflowTitle: "Typical weekly workflow",
                weeklyWorkflow: [
                    "problem modeling",
                    "solver implementation",
                    "ablation studies",
                    "result discussion"
                ]
            },
            {
                theme: "Human-Centered AI",
                skillsTitle: "Helpful skills",
                skills: [
                    "HCI basics",
                    "explainable AI",
                    "frontend prototyping",
                    "user study design"
                ],
                firstProjectTitle: "Good first project",
                firstProjectIdea: "Prototype an explanation panel for one model and evaluate it with a small user study.",
                weeklyWorkflowTitle: "Typical weekly workflow",
                weeklyWorkflow: [
                    "interface iteration",
                    "user feedback collection",
                    "analysis",
                    "team critique"
                ]
            },
            {
                theme: "Cyber-Physical Infrastructure",
                skillsTitle: "Helpful skills",
                skills: [
                    "distributed systems",
                    "container ops",
                    "sensor integration",
                    "monitoring"
                ],
                firstProjectTitle: "Good first project",
                firstProjectIdea: "Build a fault-injection script and measure end-to-end recovery behavior.",
                weeklyWorkflowTitle: "Typical weekly workflow",
                weeklyWorkflow: [
                    "system implementation",
                    "integration tests",
                    "failure drills",
                    "design review"
                ]
            }
        ],
        processTitle: "Research Process and Culture",
        process: [
            {
                title: "Topic Selection",
                description: "We start from concrete problems, survey related work, and define measurable milestones."
            },
            {
                title: "Mentoring Cadence",
                description: "Students receive weekly one-on-one or small-group feedback to maintain steady progress."
            },
            {
                title: "Publication Pipeline",
                description: "We run internal checkpoints from experiment design to writing, revision, and submission."
            },
            {
                title: "Collaboration Style",
                description: "Pair reviews, transparent experiment logs, and reproducibility are standard expectations."
            }
        ],
        faqTitle: "Research FAQ",
        faqs: [
            {
                question: "Do I need prior publications before joining a topic?",
                answer: "No. We prioritize curiosity, consistency, and willingness to learn over an existing publication record."
            },
            {
                question: "What language is used for research meetings?",
                answer: "We use both Japanese and English depending on participants, and we support international members."
            },
            {
                question: "How long does it take to start producing results?",
                answer: "Most students complete onboarding and begin reproducible experiments within the first semester."
            },
            {
                question: "Can I work across multiple themes?",
                answer: "Yes. Cross-theme projects are encouraged when there is a clear research question and scoped milestones."
            }
        ],
        ctaTitle: "Next Steps",
        ctas: {
            publications: "See Publications",
            joinUs: "Join Us",
            contact: "Contact for Research Discussion"
        }
    },
    publications: {
        title: "Publications",
        subtitle: "A continuously updated list of papers, journal articles, and conference publications.",
        noItemsTitle: "No publications yet",
        noItemsBody: "Add publication entries from the admin dashboard.",
        linkLabel: "Publication link",
        teaserAltSuffix: "teaser",
        searchLabel: "Search",
        searchPlaceholder: "Search by title, authors, venue, or abstract",
        yearFilterLabel: "Year",
        venueFilterLabel: "Venue",
        allYears: "All years",
        allVenues: "All venues",
        sortLabel: "Sort",
        sortNewest: "Newest first",
        sortOldest: "Oldest first",
        sortTitleAsc: "Title A-Z",
        sortTitleDesc: "Title Z-A",
        pageLabel: "Publication pagination",
        previousPage: "Previous",
        nextPage: "Next",
        pageSummary: "Showing {from}-{to} of {total} publications",
        noResultsTitle: "No matching publications",
        noResultsBody: "Try changing your search keyword or filters.",
        clearFilters: "Clear search and filters",
        paperAriaLabel: "Paper",
        projectAriaLabel: "Project page",
        codeAriaLabel: "Code"
    },
    members: {
        title: "Members",
        subtitle: "Our team includes faculty, researchers, and students working across data-driven science and engineering.",
        noItemsTitle: "No members yet",
        noItemsBody: "Add member profiles from the admin dashboard.",
        researchTopicLabel: "Research Topic",
        personalPage: "Personal page",
        photoAltSuffix: "photo"
    },
    joinUs: {
        title: "Join Us",
        subtitle: "Build impactful research with a team that values rigor, openness, and curiosity.",
        hero: {
            headline: "Grow your research in a collaborative lab culture.",
            pitch: "At HaseLab, you will work on real problems, receive hands-on mentoring, and publish with a team that supports each member's long-term growth.",
            highlights: [
                "Close advising and regular research feedback loops",
                "Opportunities to publish and present at top venues",
                "An international and interdisciplinary team environment"
            ],
            primaryCta: "Start Your Application",
            secondaryCta: "Contact the Lab"
        },
        openPositionsTitle: "Open Positions",
        openPositions: [
            {
                role: "PhD / MSc Research Students",
                requirementLabel: "Requirements",
                requirements: [
                    "Strong interest in machine learning, optimization, or ubiquitous AI",
                    "Ability to read and discuss technical papers in English",
                    "Programming experience (Python or similar)"
                ]
            },
            {
                role: "Research Interns (Undergraduate / External)",
                requirementLabel: "Requirements",
                requirements: [
                    "Basic coding and data analysis skills",
                    "Commitment of at least one academic term or summer period",
                    "Interest in implementing and validating research ideas"
                ]
            },
            {
                role: "Visiting Researchers / Collaborators",
                requirementLabel: "Requirements",
                requirements: [
                    "Clear research alignment with our ongoing topics",
                    "Defined collaboration goal and timeline",
                    "Institutional support for the visit period"
                ]
            }
        ],
        whatWeLookForTitle: "What We Look For",
        whatWeLookFor: [
            {
                category: "Skills",
                points: [
                    "Foundational understanding of statistics, machine learning, or optimization",
                    "Practical coding and experiment reproducibility habits",
                    "Clear written and spoken communication"
                ]
            },
            {
                category: "Mindset",
                points: [
                    "Curiosity to ask deep questions and iterate",
                    "Ownership from idea to implementation and reporting",
                    "Respectful collaboration and constructive feedback"
                ]
            },
            {
                category: "Background",
                points: [
                    "Engineering, CS, data science, applied math, or related fields",
                    "Prior projects, thesis, or research experience is a plus",
                    "Motivation matters as much as your current level"
                ]
            }
        ],
        howToApplyTitle: "How To Apply",
        applySteps: [
            "Submit the application form from the button below.",
            "We will review the application and send a notification whether you are qualified.",
            "If you have been qualified, we will send an email with a more detailed procedure based on your context."
        ],
        contactCta: "Submit Application Form",
        faqTitle: "FAQ",
        faqs: [
            {
                question: "What kind of research topics can I work on in this lab?",
                description: "We cover a wide range of research from theory to application in artificial intelligence and human-machine interaction. We can accommodate pretty much anything, so if you have a topic in mind, feel free to consult with a senior student or Hasegawa first."
            },
            {
                question: "Are there any required skills or knowledge (programming, math, etc.) before joining the lab?",
                description: "Nothing in particular is required, but having basic coding ability and mathematical knowledge (linear algebra, calculus, vectors, and probability/statistics) will make things much easier after you join, as these are foundational for studying deep learning."
            },
            {
                question: "What does a typical day or lifestyle in the lab look like?",
                description: "There is basically no core time, so everyone comes in and does their research at whatever time works for them. It's pretty flexible. For more details, please see:",
                links: [
                    {
                        label: "see these infos (Student Schedules)",
                        href: "https://example.com"
                    }
                ]
            },
            {
                question: "What is the supervision style like? (Strict, flexible, meeting frequency, etc.)",
                description: "We value student independence, while also holding weekly one-on-one meetings to make sure students don't get stuck."
            },
            {
                question: "What is the lab atmosphere and dynamic like among members?",
                description: "We have casual drinking parties in the lab from time to time, and people chat during breaks. It's a relaxed and easygoing environment."
            },
            {
                question: "What are the typical career paths after graduation? (Employment, further study, etc.)",
                description: "The ratio is roughly 20% employment to 80% further study. Among students who complete a master's degree, some go on to join major companies such as CyberAgent, Hitachi, and Nomura Research Institute. For more details, please see:",
                links: [
                    {
                        label: "see these infos (Career Paths of Lab Alumni)",
                        href: "https://example.com"
                    }
                ]
            },
            {
                question: "How is the research topic decided? (Can I choose it myself, or is it assigned?)",
                description: "We prioritize each student's own interests and initiative. If you can't think of a topic, we can suggest one for you."
            },
            {
                question: "How many opportunities are there to write papers or present at conferences?",
                description: "It varies depending on each student's preferences, but undergraduate students typically present at one domestic conference per year, while graduate students often present at international conferences about twice a year. Paper writing follows a similar pattern."
            },
            {
                question: "Are there any activities outside of research? (Events, collaborative research, industry partnerships, etc.)",
                description: "We regularly hold BBQs, drinking parties, and retreats. We also engage in joint research and partnerships with companies."
            },
            {
                question: "Is there a core time or mandatory hours? Is it possible to balance lab work with a part-time job?",
                description: "There is no core time or mandatory hours. Balancing with a part-time job is absolutely possible."
            }
        ],
        testimonialsTitle: "Testimonials",
        testimonials: [
            {
                quote: "The lab gave me both freedom and structure. Weekly feedback helped me turn rough ideas into a conference paper.",
                name: "MSc Graduate",
                background: "Now PhD student in AI"
            },
            {
                quote: "As an intern, I was trusted with real experiments from day one. The team culture made it easy to ask questions.",
                name: "Research Intern",
                background: "Undergraduate in Computer Science"
            },
            {
                quote: "Our collaboration moved quickly because discussions were concrete and technical depth was always present.",
                name: "Visiting Researcher",
                background: "Partner university faculty"
            }
        ]
    },
    business: {
        title: "Business",
        subtitle: "Industry and social collaborations are central to how we create real-world impact from research.",
        items: [
            {
                title: "Joint Research",
                description: "We collaborate with industry and public organizations to solve practical, data-intensive challenges."
            },
            {
                title: "Technical Consulting",
                description: "Our lab provides expertise in machine learning strategy, model deployment, and optimization workflows."
            },
            {
                title: "Student-Industry Projects",
                description: "We organize project-based collaborations that connect academic research with product and operational needs."
            }
        ]
    },
    contact: {
        title: "Contact",
        subtitle: "We welcome research, education, and industry inquiries.",
        generalInfoTitle: "General Information",
        inquiryGuideTitle: "Inquiry Guide",
        studentGuide: "For student applications, include your CV, research interests, and expected start period.",
        businessGuide: "For business collaboration, include your project background, timeline, and expected outcomes.",
        labels: {
            email: "Email",
            address: "Address"
        }
    },
    blogs: {
        title: "Blogs",
        subtitle: "Articles are written in Markdown and automatically rendered into the website.",
        noItemsTitle: "No blog posts yet",
        noItemsBody: "Create your first post from the admin dashboard.",
        readArticle: "Read article",
        publishedPrefix: "Published"
    },
    news: {
        title: "News",
        subtitle: "Recent activities, announcements, and updates from our laboratory.",
        noItemsTitle: "No news yet",
        noItemsBody: "Create your first news item from the admin dashboard.",
        visitExternal: "Visit external page",
        moreDetails: "More details",
        searchLabel: "Search",
        searchPlaceholder: "Search by title, content, type, or highlight",
        typeFilterLabel: "Type",
        allTypes: "All types",
        sortLabel: "Sort",
        sortNewest: "Newest first",
        sortOldest: "Oldest first",
        sortTitleAsc: "Title A-Z",
        sortTitleDesc: "Title Z-A",
        pageLabel: "News pagination",
        previousPage: "Previous",
        nextPage: "Next",
        pageSummary: "Showing {from}-{to} of {total} news",
        noResultsTitle: "No matching news",
        noResultsBody: "Try changing your search keyword or filters.",
        clearFilters: "Clear search and filters"
    }
};
}),
"[project]/src/lib/i18n/messages/ja.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "jaMessages",
    ()=>jaMessages
]);
const jaMessages = {
    metadata: {
        siteTitle: "長谷川研究室",
        siteDescription: "研究、出版物、メンバー、管理画面からの更新を備えた研究室ホームページ。"
    },
    header: {
        brandTitle: "長谷川研究室",
        brandSubtitle: "ユビキタス知能を創る。",
        mainNavAria: "メインナビゲーション",
        languageLabel: "言語",
        languages: {
            en: "EN",
            ja: "日本語",
            zh: "中文"
        },
        nav: {
            home: "ホーム",
            research: "研究",
            news: "ニュース",
            blogs: "ブログ",
            publications: "出版物",
            members: "メンバー",
            joinUs: "参加案内",
            business: "産学連携",
            contact: "Contact Us"
        }
    },
    footer: {
        copyright: "福井大学 長谷川研究室"
    },
    notFound: {
        title: "ページが見つかりません",
        description: "お探しのページは存在しません。",
        cta: "ホームに戻る"
    },
    home: {
        badge: "長谷川研究室",
        title: "ユビキタスと知能を繋ぐ",
        intro: "私たちは、モバイルセンシングと深層学習を通じて、人・デバイス・知識をつなぐ知能システムの実現を目指しています。",
        primaryCta: "For Students",
        secondaryCta: "See Research",
        aboutTitle: "About Us",
        aboutBody: "長谷川研究室はユビキタス人工知能を中心に研究しています。基盤モデルの活用、新しいニューラルアーキテクチャの開発、ニューラルネットワークのメカニズム解明に取り組んでいます。",
        aboutCta: "See research",
        latestNewsTitle: "Latest News",
        noNewsTitle: "ニュースはまだありません",
        noNewsBody: "管理画面からニュースを追加すると、ここに表示されます。",
        viewAllNews: "Browse News",
        latestProjectTitle: "Featured Projects",
        featuredPublicationsTitle: "Featured Publications",
        viewAllPublications: "Browse Publications",
        visitProject: "Browse Projects",
        noProject: "管理画面からプロジェクトを追加すると、ここに表示されます。",
        contactTitle: "Contact Us",
        quickInquiryTitle: "クイックお問い合わせ",
        quickInquiryBody: "ご経歴、研究関心、希望開始時期をお知らせください。通常は数営業日以内に返信します。",
        generalInfoTitle: "基本情報",
        viewContactDetails: "連絡先の詳細を見る",
        sendEmailCta: "メールを送る",
        labels: {
            email: "メール",
            address: "住所"
        }
    },
    research: {
        title: "研究",
        subtitle: "私たちが何に取り組み、どのような成果を出し、どこで新しい学生が参加できるかを示します。",
        vision: {
            missionTitle: "研究ビジョン",
            missionStatement: "科学的厳密性・実装可能性・人間中心設計を両立したユビキタス知能システムを創出します。",
            focusQuestionsTitle: "現在の重点課題",
            focusQuestions: [
                "汎用人工知能の実現に向けて、どのようなデータが不足しているのか？",
                "基盤モデルからタスク特化型モデルをどのように構築できるか？",
                "小規模モデルのアンサンブルは、単一の大規模モデルに匹敵できるか？",
                "基盤モデルは、どのような世界モデルを獲得しているのか？",
                "高信頼な識別モデルはどのように構築できるか？"
            ],
            imageAlt: "ダッシュボードを前に実験結果を議論する学生",
            imageCaption: "研究の基本サイクル: 課題設定、反復実験、週次のエビデンスレビュー。"
        },
        themesTitle: "研究テーマ",
        themes: [
            {
                title: "機械学習・データ知能",
                description: "ノイズ環境に対応する表現学習、頑健学習、適応的データパイプラインを研究します。",
                whyItMatters: "実運用でデータ品質が揺らぐ状況でも信頼できるモデルが必要です。",
                methods: "自己教師あり学習、不確実性推定、ストリーミングデータ検証。",
                outputs: "国際会議論文、ベンチマークデータセット、再現可能な学習レシピ。"
            },
            {
                title: "最適化・意思決定システム",
                description: "大規模・不確実・動的システム向けの数理最適化と計画手法を探究します。",
                whyItMatters: "意思決定品質の改善は安全性・効率・資源利用に直結します。",
                methods: "制約付き最適化、MPC 型計画、シミュレーション評価。",
                outputs: "ソルバーツール、意思決定シミュレータ、実証ケースレポート。"
            },
            {
                title: "人間中心AI",
                description: "社会・産業で実用可能な、説明可能かつ協調的な AI システムを設計します。",
                whyItMatters: "社会実装には透明性、使いやすさ、人間の適切な介入設計が不可欠です。",
                methods: "解釈可能モデル、ユーザ評価、実務者との共創設計。",
                outputs: "インタフェース試作、設計ガイドライン、実証的なユーザ評価結果。"
            },
            {
                title: "サイバーフィジカル基盤",
                description: "センシング・制御・運用とデジタル知能をつなぐ高信頼アーキテクチャを研究します。",
                whyItMatters: "実世界で成果を出すには、障害に強い運用基盤が必要です。",
                methods: "エッジ・クラウド協調、障害耐性パイプライン、デジタルツイン検証。",
                outputs: "デプロイデモ、基盤設計指針、産学連携の実証プロジェクト。"
            }
        ],
        themeLabels: {
            whyItMatters: "重要性",
            methods: "手法・ツール",
            outputs: "成果例",
            imagePlaceholder: "画像"
        },
        projectLabels: {
            problem: "課題",
            approach: "アプローチ",
            status: "ステータス"
        },
        projectsTitle: "進行中プロジェクト",
        projects: [
            {
                title: "ノイズ環境下モバイルセンシングの適応学習",
                problem: "ユーザ・端末・文脈の違いにより、データ品質が時間とともに変化します。",
                approach: "信頼度に基づくデータ選択とオンライン再較正を組み合わせて頑健性を高めます。",
                status: "進行中",
                paperUrl: "/publications",
                codeUrl: "https://github.com",
                demoUrl: "/blogs"
            },
            {
                title: "動的環境における安全な意思決定最適化",
                problem: "環境条件や制約の変化で、ポリシーが容易に劣化する可能性があります。",
                approach: "予測計画と制約付き最適化を統合し、ストレステストで性能を検証します。",
                status: "進行中",
                paperUrl: "/publications",
                demoUrl: "/news"
            },
            {
                title: "専門家向け説明可能 AI コパイロット",
                problem: "実務者にはスコアだけでなく、改善につながる説明が必要です。",
                approach: "インタラクティブ説明 UI とフィードバックループを設計し、誤り分析を行います。",
                status: "公開済み",
                paperUrl: "/publications",
                demoUrl: "/blogs"
            },
            {
                title: "ユビキタス AI 向け耐障害エッジ・クラウド基盤",
                problem: "通信断や部分故障時に推論パイプラインが性能低下します。",
                approach: "フォールバック制御と復旧戦略を設計し、デジタルツインで検証します。",
                status: "企画中",
                demoUrl: "/news"
            }
        ],
        projectLinks: {
            paper: "論文",
            code: "コード",
            demo: "デモ"
        },
        outcomesTitle: "成果とインパクト",
        outcomesSubtitle: "論文、実装、連携の観点から代表的な成果を示します。",
        outcomes: [
            {
                title: "主要論文",
                description: "機械学習、最適化、ユビキタスシステム領域での査読付き成果。"
            },
            {
                title: "受賞・外部評価",
                description: "学生表彰、競争的資金採択、国内外での招待講演。"
            },
            {
                title: "社会実装・共同研究",
                description: "実運用課題を対象とした大学・企業との共同プロジェクト。"
            }
        ],
        byNumbersTitle: "数字で見る研究室",
        byNumbers: [
            {
                value: "12+",
                label: "過去1年の論文数"
            },
            {
                value: "6",
                label: "進行中の共同研究"
            },
            {
                value: "4",
                label: "公開中の研究リポジトリ"
            },
            {
                value: "15+",
                label: "指導した学位研究"
            }
        ],
        joinByTopicTitle: "テーマ別 参加ガイド",
        joinByTopic: [
            {
                theme: "機械学習・データ知能",
                skillsTitle: "あると良いスキル",
                skills: [
                    "Python",
                    "PyTorch",
                    "前処理",
                    "実験管理"
                ],
                firstProjectTitle: "最初の課題例",
                firstProjectIdea: "既存ベースラインを再現し、人工ノイズ条件で頑健性改善を試します。",
                weeklyWorkflowTitle: "週次の進め方",
                weeklyWorkflow: [
                    "論文読解",
                    "実装",
                    "実験",
                    "週次レビュー"
                ]
            },
            {
                theme: "最適化・意思決定システム",
                skillsTitle: "あると良いスキル",
                skills: [
                    "線形代数",
                    "最適化",
                    "シミュレーション",
                    "アルゴリズム設計"
                ],
                firstProjectTitle: "最初の課題例",
                firstProjectIdea: "制約付き計画のベースラインを実装し、外乱下で性能比較を行います。",
                weeklyWorkflowTitle: "週次の進め方",
                weeklyWorkflow: [
                    "問題定式化",
                    "ソルバー実装",
                    "アブレーション",
                    "結果議論"
                ]
            },
            {
                theme: "人間中心AI",
                skillsTitle: "あると良いスキル",
                skills: [
                    "HCI基礎",
                    "説明可能AI",
                    "UI 試作",
                    "ユーザ調査設計"
                ],
                firstProjectTitle: "最初の課題例",
                firstProjectIdea: "1つのモデル向け説明 UI を試作し、小規模ユーザ評価を実施します。",
                weeklyWorkflowTitle: "週次の進め方",
                weeklyWorkflow: [
                    "UI 改善",
                    "フィードバック収集",
                    "分析",
                    "チームレビュー"
                ]
            },
            {
                theme: "サイバーフィジカル基盤",
                skillsTitle: "あると良いスキル",
                skills: [
                    "分散システム",
                    "コンテナ運用",
                    "センサ連携",
                    "監視基盤"
                ],
                firstProjectTitle: "最初の課題例",
                firstProjectIdea: "障害注入スクリプトを作成し、復旧性能を計測します。",
                weeklyWorkflowTitle: "週次の進め方",
                weeklyWorkflow: [
                    "システム実装",
                    "統合試験",
                    "障害訓練",
                    "設計レビュー"
                ]
            }
        ],
        processTitle: "研究プロセスとカルチャー",
        process: [
            {
                title: "テーマ設計",
                description: "実課題を起点に先行研究を整理し、検証可能なマイルストーンを設定します。"
            },
            {
                title: "メンタリング",
                description: "週次の個別または少人数ミーティングで、継続的に研究を前進させます。"
            },
            {
                title: "論文化プロセス",
                description: "実験設計から執筆・改稿・投稿まで、段階的な内部チェックを実施します。"
            },
            {
                title: "協働スタイル",
                description: "ペアレビュー、実験ログ共有、再現性重視を標準運用としています。"
            }
        ],
        faqTitle: "研究 FAQ",
        faqs: [
            {
                question: "参加時点で論文実績は必要ですか？",
                answer: "必須ではありません。実績よりも、学ぶ姿勢と継続力を重視します。"
            },
            {
                question: "研究ミーティングの使用言語は何ですか？",
                answer: "参加者に応じて日本語と英語を使い分け、留学生も参加しやすい運営を行います。"
            },
            {
                question: "成果が出るまでの目安はありますか？",
                answer: "多くの学生は最初の学期でオンボーディングを終え、再現実験を開始します。"
            },
            {
                question: "複数テーマを横断して取り組めますか？",
                answer: "はい。明確な研究課題と計画があれば、横断テーマを歓迎します。"
            }
        ],
        ctaTitle: "次のステップ",
        ctas: {
            publications: "出版物を見る",
            joinUs: "参加案内を見る",
            contact: "研究相談をする"
        }
    },
    publications: {
        title: "出版物",
        subtitle: "論文誌・国際会議・各種論文を継続的に更新しています。",
        noItemsTitle: "出版物はまだありません",
        noItemsBody: "管理画面から出版物を追加してください。",
        linkLabel: "論文リンク",
        teaserAltSuffix: "ティザー",
        searchLabel: "検索",
        searchPlaceholder: "タイトル、著者、掲載先、要旨で検索",
        yearFilterLabel: "年",
        venueFilterLabel: "掲載先",
        allYears: "すべての年",
        allVenues: "すべての掲載先",
        sortLabel: "並び替え",
        sortNewest: "新しい順",
        sortOldest: "古い順",
        sortTitleAsc: "タイトル昇順",
        sortTitleDesc: "タイトル降順",
        pageLabel: "出版物ページネーション",
        previousPage: "前へ",
        nextPage: "次へ",
        pageSummary: "{total} 件中 {from}-{to} 件を表示",
        noResultsTitle: "該当する出版物がありません",
        noResultsBody: "検索キーワードやフィルター条件を変更してください。",
        clearFilters: "検索・フィルターをクリア",
        paperAriaLabel: "論文",
        projectAriaLabel: "プロジェクトページ",
        codeAriaLabel: "コード"
    },
    members: {
        title: "メンバー",
        subtitle: "教員、研究者、学生がデータ駆動型の科学技術に取り組んでいます。",
        noItemsTitle: "メンバー情報はまだありません",
        noItemsBody: "管理画面からメンバー情報を追加してください。",
        researchTopicLabel: "研究テーマ",
        personalPage: "個人ページ",
        photoAltSuffix: "写真"
    },
    joinUs: {
        title: "参加案内",
        subtitle: "厳密さと挑戦を大切にしながら、社会に届く研究を一緒に進めましょう。",
        hero: {
            headline: "協働的な環境で、研究力を次の段階へ。",
            pitch: "長谷川研究室では、実課題に取り組みながら、密な指導と継続的なフィードバックを通じて、一人ひとりの成長を支援します。",
            highlights: [
                "定期的な研究ディスカッションと個別メンタリング",
                "トップ会議・論文投稿を見据えた研究推進",
                "多様な背景を持つメンバーとの国際的な協働"
            ],
            primaryCta: "応募を始める",
            secondaryCta: "研究室に連絡する"
        },
        openPositionsTitle: "募集ポジション",
        openPositions: [
            {
                role: "博士・修士課程学生",
                requirementLabel: "応募要件",
                requirements: [
                    "機械学習・最適化・ユビキタス AI への強い関心",
                    "英語文献を読み、議論できる基礎力",
                    "Python などのプログラミング経験"
                ]
            },
            {
                role: "研究インターン（学部生・学外）",
                requirementLabel: "応募要件",
                requirements: [
                    "基礎的な実装力とデータ解析スキル",
                    "学期または夏季期間での継続参加",
                    "仮説検証を粘り強く進める姿勢"
                ]
            },
            {
                role: "訪問研究員・共同研究者",
                requirementLabel: "応募要件",
                requirements: [
                    "研究室テーマとの明確な整合",
                    "具体的な共同研究目標と期間設定",
                    "所属機関での受入・派遣調整"
                ]
            }
        ],
        whatWeLookForTitle: "求める人物像",
        whatWeLookFor: [
            {
                category: "スキル",
                points: [
                    "統計・機械学習・最適化の基礎理解",
                    "再現性を意識した実装と実験管理",
                    "論理的で明確なコミュニケーション"
                ]
            },
            {
                category: "マインドセット",
                points: [
                    "深く問い続ける好奇心",
                    "課題設定から報告までやり切る主体性",
                    "建設的に協働する姿勢"
                ]
            },
            {
                category: "バックグラウンド",
                points: [
                    "情報・工学・数理・データ科学など関連分野",
                    "研究・卒業研究・開発経験があれば歓迎",
                    "現在のスキル以上に意欲と継続力を重視"
                ]
            }
        ],
        howToApplyTitle: "応募方法",
        applySteps: [
            "下のボタンから応募フォームを提出してください。",
            "応募内容を確認し、適格かどうかをお知らせします。",
            "適格と判断された場合、状況に応じた詳細手続きをメールでご案内します。"
        ],
        contactCta: "応募フォームを送信",
        faqTitle: "よくある質問",
        faqs: [
            {
                question: "学生向けの資金支援はありますか？",
                description: "支援内容はプログラムやプロジェクトによって異なります。選考過程で、利用可能な奨学金や RA 等の制度をご案内します。"
            },
            {
                question: "留学生の応募とビザ手続きに対応していますか？",
                description: "はい、対応しています。合格後は大学の手続きに沿って、必要書類の準備と申請手順をサポートします。"
            },
            {
                question: "参加前に必要な前提知識はありますか？",
                description: "特定ツールの必須条件はありませんが、基礎的なプログラミング力と数理的素養を想定しています。学ぶ意欲を重視します。"
            }
        ],
        testimonialsTitle: "メンバーの声",
        testimonials: [
            {
                quote: "週次の議論がとても密で、曖昧だったアイデアを論文レベルまで磨くことができました。",
                name: "修士修了生",
                background: "現 AI 分野 博士課程"
            },
            {
                quote: "インターンでも本格的な実験を任せてもらえ、質問しやすい雰囲気で成長できました。",
                name: "研究インターン",
                background: "情報系学部生"
            },
            {
                quote: "共同研究の議論が具体的で、短期間でも成果につながる進め方ができました。",
                name: "訪問研究者",
                background: "連携大学 教員"
            }
        ]
    },
    business: {
        title: "産学連携",
        subtitle: "産業界や社会との連携は、研究成果を実世界へ届けるうえで中核となる活動です。",
        items: [
            {
                title: "共同研究",
                description: "産業界や公共機関と連携し、実務的でデータ集約型の課題解決に取り組みます。"
            },
            {
                title: "技術コンサルティング",
                description: "機械学習戦略、モデル運用、最適化ワークフローに関する専門知見を提供します。"
            },
            {
                title: "学生連携プロジェクト",
                description: "研究と製品・運用ニーズを結びつけるプロジェクト型連携を企画・実施します。"
            }
        ]
    },
    contact: {
        title: "お問い合わせ",
        subtitle: "研究・教育・産学連携に関するお問い合わせを歓迎します。",
        generalInfoTitle: "基本情報",
        inquiryGuideTitle: "お問い合わせガイド",
        studentGuide: "学生応募の際は、履歴書、研究関心、希望開始時期をご記載ください。",
        businessGuide: "企業連携の際は、プロジェクト背景、スケジュール、期待成果をご記載ください。",
        labels: {
            email: "メール",
            address: "住所"
        }
    },
    blogs: {
        title: "ブログ",
        subtitle: "記事は Markdown で作成され、Web サイトに自動反映されます。",
        noItemsTitle: "ブログ記事はまだありません",
        noItemsBody: "管理画面から最初の記事を作成してください。",
        readArticle: "記事を読む",
        publishedPrefix: "公開日"
    },
    news: {
        title: "ニュース",
        subtitle: "研究室の最近の活動・お知らせ・更新情報を掲載しています。",
        noItemsTitle: "ニュースはまだありません",
        noItemsBody: "管理画面から最初のニュースを作成してください。",
        visitExternal: "外部ページを見る",
        moreDetails: "詳細を見る",
        searchLabel: "検索",
        searchPlaceholder: "タイトル、本文、種別、ハイライトで検索",
        typeFilterLabel: "種別",
        allTypes: "すべての種別",
        sortLabel: "並び替え",
        sortNewest: "新しい順",
        sortOldest: "古い順",
        sortTitleAsc: "タイトル昇順",
        sortTitleDesc: "タイトル降順",
        pageLabel: "ニュースページネーション",
        previousPage: "前へ",
        nextPage: "次へ",
        pageSummary: "{total} 件中 {from}-{to} 件を表示",
        noResultsTitle: "該当するニュースがありません",
        noResultsBody: "検索キーワードやフィルター条件を変更してください。",
        clearFilters: "検索・フィルターをクリア"
    }
};
}),
"[project]/src/lib/i18n/messages/zh.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "zhMessages",
    ()=>zhMessages
]);
const zhMessages = {
    metadata: {
        siteTitle: "长谷川实验室",
        siteDescription: "包含研究、出版物、成员以及可由管理后台更新内容的实验室主页。"
    },
    header: {
        brandTitle: "长谷川实验室",
        brandSubtitle: "构建无处不在的智能。",
        mainNavAria: "主导航",
        languageLabel: "语言",
        languages: {
            en: "EN",
            ja: "日本語",
            zh: "中文"
        },
        nav: {
            home: "首页",
            research: "研究",
            news: "动态",
            blogs: "博客",
            publications: "出版物",
            members: "成员",
            joinUs: "加入我们",
            business: "合作",
            contact: "联系我们"
        }
    },
    footer: {
        copyright: "福井大学 长谷川实验室"
    },
    notFound: {
        title: "页面不存在",
        description: "您访问的页面不存在。",
        cta: "返回首页"
    },
    home: {
        badge: "长谷川实验室",
        title: "连接无处不在与智能",
        intro: "我们的使命是通过移动感知与深度学习，构建连接人与设备与知识的智能系统。",
        primaryCta: "申请加入",
        secondaryCta: "查看研究",
        aboutTitle: "关于我们",
        aboutBody: "长谷川实验室聚焦于泛在人工智能研究。我们探索如何利用基础模型能力、开发新一代神经网络架构，并加深对神经网络机制的理解。",
        aboutCta: "查看研究方向",
        latestNewsTitle: "最新动态",
        noNewsTitle: "暂无动态",
        noNewsBody: "在管理后台添加动态后，将显示在这里。",
        viewAllNews: "查看全部动态",
        latestProjectTitle: "最新项目",
        featuredPublicationsTitle: "代表性出版物",
        viewAllPublications: "查看全部出版物",
        visitProject: "查看项目页面",
        noProject: "请在管理后台添加项目以在此展示。",
        contactTitle: "联系我们",
        quickInquiryTitle: "快速咨询",
        quickInquiryBody: "请告诉我们你的背景、研究兴趣和希望开始时间。我们通常会在几个工作日内回复。",
        generalInfoTitle: "基本信息",
        viewContactDetails: "查看完整联系信息",
        sendEmailCta: "立即发邮件",
        labels: {
            email: "邮箱",
            address: "地址"
        }
    },
    research: {
        title: "研究",
        subtitle: "清晰展示实验室在做什么、产出什么成果，以及学生可以从哪里开始参与。",
        vision: {
            missionTitle: "研究愿景",
            missionStatement: "构建兼具科学严谨性、工程可落地性与以人为中心设计的泛在智能系统。",
            focusQuestionsTitle: "当前核心问题",
            focusQuestions: [
                "实现通用人工智能还缺少哪些关键数据？",
                "如何从基础模型构建面向具体任务的专用模型？",
                "多个小模型的集成能否媲美单个大模型？",
                "基础模型究竟学到了什么样的世界模型？",
                "如何构建高度可靠的判别模型？"
            ],
            imageAlt: "学生在仪表盘前讨论实验结果",
            imageCaption: "实验室常见研究循环：问题定义、迭代实验、每周基于证据的评审。"
        },
        themesTitle: "研究主题",
        themes: [
            {
                title: "机器学习与数据智能",
                description: "研究表征学习、鲁棒训练与面向噪声环境的自适应数据管线。",
                whyItMatters: "真实部署中数据质量会波动，模型稳定性是前提。",
                methods: "自监督学习、不确定性估计、流式数据质量校验。",
                outputs: "会议论文、基准数据集、可复现实验流程。"
            },
            {
                title: "优化与决策系统",
                description: "面向大规模、不确定与动态系统的数学优化与规划方法。",
                whyItMatters: "决策质量直接影响安全性、效率和资源利用。",
                methods: "约束优化、MPC 风格规划、仿真驱动评估。",
                outputs: "求解器工具、决策仿真器、场景化验证报告。"
            },
            {
                title: "以人为中心的 AI",
                description: "设计可解释、可协作，并适用于社会与产业场景的 AI 系统。",
                whyItMatters: "只有透明、易用并具有人机协同机制的系统才能被真正采用。",
                methods: "可解释建模、用户研究、与实践方协同设计工作流。",
                outputs: "交互原型、设计准则、用户评估结果。"
            },
            {
                title: "信息物理基础设施",
                description: "构建连接数字智能与现实感知、控制、运行的高韧性架构。",
                whyItMatters: "研究成果要落地，必须具备跨设备、跨网络的稳定运行能力。",
                methods: "边云协同、故障容错管线、数字孪生验证。",
                outputs: "部署演示、架构蓝图、校企联合试点。"
            }
        ],
        themeLabels: {
            whyItMatters: "意义",
            methods: "方法与工具",
            outputs: "成果示例",
            imagePlaceholder: "图片"
        },
        projectLabels: {
            problem: "问题",
            approach: "方案",
            status: "状态"
        },
        projectsTitle: "在研项目",
        projects: [
            {
                title: "噪声移动感知数据的自适应学习",
                problem: "不同用户、设备与场景会导致数据分布和质量持续变化。",
                approach: "结合置信度驱动的数据选择与在线重校准，提高模型鲁棒性。",
                status: "进行中",
                paperUrl: "/publications",
                codeUrl: "https://github.com",
                demoUrl: "/blogs"
            },
            {
                title: "动态环境下的安全决策优化",
                problem: "当约束或运行条件变化时，策略容易失效。",
                approach: "融合预测规划与约束优化，并通过压力测试仿真验证稳定性。",
                status: "进行中",
                paperUrl: "/publications",
                demoUrl: "/news"
            },
            {
                title: "面向领域专家的可解释 AI 协作助手",
                problem: "专家需要可执行的解释，而不仅是模型分数。",
                approach: "构建交互式解释界面，结合迭代反馈与误差分析。",
                status: "已发表",
                paperUrl: "/publications",
                demoUrl: "/blogs"
            },
            {
                title: "泛在 AI 的韧性边云基础设施",
                problem: "网络波动和部分硬件故障会导致推理链路退化。",
                approach: "设计降级调度与服务恢复机制，并在数字孪生环境中验证。",
                status: "方案阶段",
                demoUrl: "/news"
            }
        ],
        projectLinks: {
            paper: "论文",
            code: "代码",
            demo: "演示"
        },
        outcomesTitle: "成果与影响",
        outcomesSubtitle: "从论文、部署与合作三个维度展示代表性成果。",
        outcomes: [
            {
                title: "代表性论文",
                description: "在机器学习、优化与泛在系统方向持续产出高质量论文。"
            },
            {
                title: "奖项与认可",
                description: "学生论文奖、项目资助以及国际学术邀请报告。"
            },
            {
                title: "部署与合作",
                description: "与高校和产业伙伴联合推进面向真实场景的研究验证。"
            }
        ],
        byNumbersTitle: "数据速览",
        byNumbers: [
            {
                value: "12+",
                label: "近一年论文产出"
            },
            {
                value: "6",
                label: "在研合作项目"
            },
            {
                value: "4",
                label: "开源研究仓库"
            },
            {
                value: "15+",
                label: "指导学生学位课题"
            }
        ],
        joinByTopicTitle: "按主题加入研究",
        joinByTopic: [
            {
                theme: "机器学习与数据智能",
                skillsTitle: "建议技能",
                skills: [
                    "Python",
                    "PyTorch",
                    "数据预处理",
                    "实验管理"
                ],
                firstProjectTitle: "入门项目",
                firstProjectIdea: "先复现基线模型，再在合成噪声条件下提升鲁棒性。",
                weeklyWorkflowTitle: "每周工作节奏",
                weeklyWorkflow: [
                    "论文阅读",
                    "代码实现",
                    "实验运行",
                    "周会复盘"
                ]
            },
            {
                theme: "优化与决策系统",
                skillsTitle: "建议技能",
                skills: [
                    "线性代数",
                    "优化方法",
                    "仿真",
                    "算法设计"
                ],
                firstProjectTitle: "入门项目",
                firstProjectIdea: "实现约束规划基线，并比较扰动条件下的性能变化。",
                weeklyWorkflowTitle: "每周工作节奏",
                weeklyWorkflow: [
                    "问题建模",
                    "求解器实现",
                    "消融实验",
                    "结果讨论"
                ]
            },
            {
                theme: "以人为中心的 AI",
                skillsTitle: "建议技能",
                skills: [
                    "HCI 基础",
                    "可解释 AI",
                    "前端原型",
                    "用户研究设计"
                ],
                firstProjectTitle: "入门项目",
                firstProjectIdea: "为单个模型构建解释面板，并完成小规模用户评估。",
                weeklyWorkflowTitle: "每周工作节奏",
                weeklyWorkflow: [
                    "界面迭代",
                    "反馈收集",
                    "分析总结",
                    "组内评审"
                ]
            },
            {
                theme: "信息物理基础设施",
                skillsTitle: "建议技能",
                skills: [
                    "分布式系统",
                    "容器运维",
                    "传感器集成",
                    "监控系统"
                ],
                firstProjectTitle: "入门项目",
                firstProjectIdea: "构建故障注入脚本并量化端到端恢复性能。",
                weeklyWorkflowTitle: "每周工作节奏",
                weeklyWorkflow: [
                    "系统开发",
                    "集成测试",
                    "故障演练",
                    "设计评审"
                ]
            }
        ],
        processTitle: "研究流程与文化",
        process: [
            {
                title: "选题方式",
                description: "从真实问题出发，结合文献调研制定可验证的里程碑。"
            },
            {
                title: "指导节奏",
                description: "每周进行一对一或小组反馈，持续推进研究质量与进度。"
            },
            {
                title: "论文管线",
                description: "从实验设计到写作、修改、投稿都有阶段性内部检查。"
            },
            {
                title: "协作方式",
                description: "强调结对评审、实验记录透明与结果可复现。"
            }
        ],
        faqTitle: "研究 FAQ",
        faqs: [
            {
                question: "加入前必须有论文经历吗？",
                answer: "不必须。我们更看重学习意愿、执行力和持续投入。"
            },
            {
                question: "组会主要使用什么语言？",
                answer: "根据参与成员使用日语与英语，并支持国际成员顺畅参与。"
            },
            {
                question: "通常多久能开始产出结果？",
                answer: "多数同学会在首个学期完成入门并开始稳定的可复现实验。"
            },
            {
                question: "可以跨多个主题做研究吗？",
                answer: "可以。只要研究问题清晰、目标可衡量，我们鼓励跨主题协作。"
            }
        ],
        ctaTitle: "下一步",
        ctas: {
            publications: "查看出版物",
            joinUs: "查看加入方式",
            contact: "联系讨论研究合作"
        }
    },
    publications: {
        title: "出版物",
        subtitle: "持续更新论文、期刊文章与会议发表列表。",
        noItemsTitle: "暂无出版物",
        noItemsBody: "请在管理后台添加出版物条目。",
        linkLabel: "论文链接",
        teaserAltSuffix: "预览图",
        searchLabel: "搜索",
        searchPlaceholder: "按标题、作者、会议或摘要搜索",
        yearFilterLabel: "年份",
        venueFilterLabel: "会议/期刊",
        allYears: "全部年份",
        allVenues: "全部会议/期刊",
        sortLabel: "排序",
        sortNewest: "最新优先",
        sortOldest: "最早优先",
        sortTitleAsc: "标题 A-Z",
        sortTitleDesc: "标题 Z-A",
        pageLabel: "出版物分页",
        previousPage: "上一页",
        nextPage: "下一页",
        pageSummary: "显示第 {from}-{to} 条，共 {total} 条",
        noResultsTitle: "没有匹配的出版物",
        noResultsBody: "请尝试调整搜索关键词或筛选条件。",
        clearFilters: "清除搜索和筛选",
        paperAriaLabel: "论文",
        projectAriaLabel: "项目页面",
        codeAriaLabel: "代码"
    },
    members: {
        title: "成员",
        subtitle: "团队由教师、研究人员和学生组成，开展数据驱动的科学与工程研究。",
        noItemsTitle: "暂无成员信息",
        noItemsBody: "请在管理后台添加成员资料。",
        researchTopicLabel: "研究主题",
        personalPage: "个人主页",
        photoAltSuffix: "照片"
    },
    joinUs: {
        title: "加入我们",
        subtitle: "在严谨、开放、互相支持的环境中，一起做有影响力的研究。",
        hero: {
            headline: "在协作型实验室里加速你的研究成长。",
            pitch: "在长谷川实验室，你将参与真实研究问题，获得持续指导，并与团队一起把想法推进到可发表、可落地的成果。",
            highlights: [
                "稳定的导师反馈与研究讨论机制",
                "面向高水平会议与期刊的研究训练",
                "跨背景、国际化的团队合作氛围"
            ],
            primaryCta: "开始申请",
            secondaryCta: "联系实验室"
        },
        openPositionsTitle: "开放岗位",
        openPositions: [
            {
                role: "博士 / 硕士研究生",
                requirementLabel: "要求",
                requirements: [
                    "对机器学习、优化或泛在 AI 有明确兴趣",
                    "能够阅读并讨论英文技术文献",
                    "具备 Python 等编程经验"
                ]
            },
            {
                role: "研究实习生（本科/校外）",
                requirementLabel: "要求",
                requirements: [
                    "具备基础编码与数据分析能力",
                    "可连续投入一个学期或暑期周期",
                    "愿意参与研究实现与实验验证"
                ]
            },
            {
                role: "访问学者 / 合作者",
                requirementLabel: "要求",
                requirements: [
                    "研究方向与实验室主题有清晰契合点",
                    "有明确合作目标与时间计划",
                    "所在机构支持访学安排"
                ]
            }
        ],
        whatWeLookForTitle: "我们看重什么",
        whatWeLookFor: [
            {
                category: "技能",
                points: [
                    "统计、机器学习或优化的基础能力",
                    "重视可复现性的编码与实验习惯",
                    "清晰的书面与口头表达能力"
                ]
            },
            {
                category: "思维方式",
                points: [
                    "持续提问并迭代的好奇心",
                    "从想法到结果的执行责任感",
                    "尊重他人、乐于协作的沟通方式"
                ]
            },
            {
                category: "背景",
                points: [
                    "计算机、工程、数据科学、应用数学等相关专业",
                    "有课程项目、论文或研究经历更佳",
                    "我们同样重视成长潜力与投入度"
                ]
            }
        ],
        howToApplyTitle: "申请流程",
        applySteps: [
            "请通过下方按钮提交申请表。",
            "我们会审核申请并通知你是否符合条件。",
            "若你通过审核，我们将根据你的情况通过邮件发送更详细的后续流程。"
        ],
        contactCta: "提交申请表",
        faqTitle: "常见问题",
        faqs: [
            {
                question: "是否提供学生资助？",
                description: "资助方式会根据项目与培养类型有所不同。我们会在选拔过程中说明可申请的奖学金与助研机会。"
            },
            {
                question: "国际学生可以申请并获得签证支持吗？",
                description: "可以。我们欢迎国际申请者。录取后会根据学校流程提供所需文件与手续支持。"
            },
            {
                question: "加入前有必须满足的先修条件吗？",
                description: "不强制要求特定工具栈，但建议具备基础编程与数学能力。我们非常看重学习意愿与持续投入。"
            }
        ],
        testimonialsTitle: "成员反馈",
        testimonials: [
            {
                quote: "实验室给了我很大的研究空间，同时每周反馈也非常扎实，帮助我把想法变成了论文。",
                name: "硕士毕业生",
                background: "现攻读 AI 博士"
            },
            {
                quote: "作为实习生，我从第一周就参与真实实验，团队氛围让提问变得很自然。",
                name: "研究实习生",
                background: "计算机本科生"
            },
            {
                quote: "合作节奏很高效，讨论始终围绕具体技术问题推进，成果产出很顺畅。",
                name: "访问研究员",
                background: "合作高校教师"
            }
        ]
    },
    business: {
        title: "合作",
        subtitle: "产业与社会合作是我们将研究转化为现实影响的重要方式。",
        items: [
            {
                title: "联合研究",
                description: "与企业及公共机构合作，解决实际且数据密集的挑战。"
            },
            {
                title: "技术咨询",
                description: "在机器学习战略、模型部署与优化流程方面提供专业支持。"
            },
            {
                title: "学生-产业项目",
                description: "组织项目制合作，连接学术研究与产品及运营需求。"
            }
        ]
    },
    contact: {
        title: "联系我们",
        subtitle: "欢迎就研究、教育和产业合作与我们联系。",
        generalInfoTitle: "基本信息",
        inquiryGuideTitle: "咨询说明",
        studentGuide: "学生申请请附上简历、研究兴趣及预计开始时间。",
        businessGuide: "业务合作请附上项目背景、时间计划与预期成果。",
        labels: {
            email: "邮箱",
            address: "地址"
        }
    },
    blogs: {
        title: "博客",
        subtitle: "文章使用 Markdown 编写，并自动渲染到网站。",
        noItemsTitle: "暂无博客文章",
        noItemsBody: "请在管理后台创建第一篇文章。",
        readArticle: "阅读全文",
        publishedPrefix: "发布日期"
    },
    news: {
        title: "动态",
        subtitle: "这里发布实验室近期活动、公告与更新。",
        noItemsTitle: "暂无动态",
        noItemsBody: "请在管理后台创建第一条动态。",
        visitExternal: "访问外部页面",
        moreDetails: "查看更多",
        searchLabel: "搜索",
        searchPlaceholder: "按标题、正文、类型或高亮搜索",
        typeFilterLabel: "类型",
        allTypes: "全部类型",
        sortLabel: "排序",
        sortNewest: "最新优先",
        sortOldest: "最早优先",
        sortTitleAsc: "标题 A-Z",
        sortTitleDesc: "标题 Z-A",
        pageLabel: "动态分页",
        previousPage: "上一页",
        nextPage: "下一页",
        pageSummary: "显示第 {from}-{to} 条，共 {total} 条",
        noResultsTitle: "没有匹配的动态",
        noResultsBody: "请尝试调整搜索关键词或筛选条件。",
        clearFilters: "清除搜索和筛选"
    }
};
}),
"[project]/src/lib/i18n/messages/index.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "getMessages",
    ()=>getMessages
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$messages$2f$en$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/i18n/messages/en.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$messages$2f$ja$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/i18n/messages/ja.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$messages$2f$zh$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/i18n/messages/zh.ts [app-rsc] (ecmascript)");
;
;
;
const messagesByLocale = {
    en: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$messages$2f$en$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["enMessages"],
    ja: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$messages$2f$ja$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jaMessages"],
    zh: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$messages$2f$zh$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["zhMessages"]
};
function getMessages(locale) {
    return messagesByLocale[locale];
}
}),
"[project]/src/lib/i18n/request-locale.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "resolveRequestLocale",
    ()=>resolveRequestLocale
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$headers$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/headers.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/i18n/config.ts [app-rsc] (ecmascript)");
;
;
async function resolveRequestLocale() {
    const cookieStore = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$headers$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cookies"])();
    const headerStore = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$headers$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["headers"])();
    const cookieLocale = cookieStore.get(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["LOCALE_COOKIE_NAME"])?.value;
    if ((0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["isLocale"])(cookieLocale)) {
        return cookieLocale;
    }
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["resolvePreferredLocale"])(headerStore.get("accept-language")) || __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DEFAULT_LOCALE"];
}
}),
"[project]/src/app/layout.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>RootLayout,
    "metadata",
    ()=>metadata
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$site$2d$footer$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/site-footer.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$site$2d$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/site-header.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/i18n/config.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$messages$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/i18n/messages/index.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$request$2d$locale$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/i18n/request-locale.ts [app-rsc] (ecmascript)");
;
;
;
;
;
;
;
const defaultMessages = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$messages$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getMessages"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DEFAULT_LOCALE"]);
const metadata = {
    title: {
        default: defaultMessages.metadata.siteTitle,
        template: `%s | ${defaultMessages.metadata.siteTitle}`
    },
    description: defaultMessages.metadata.siteDescription,
    icons: {
        icon: "/assets/logos/favicon.ico"
    }
};
async function RootLayout({ children }) {
    const locale = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$request$2d$locale$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["resolveRequestLocale"])();
    const messages = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$i18n$2f$messages$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getMessages"])(locale);
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("html", {
        lang: locale,
        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("body", {
            children: [
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                    className: "bg-orb bg-orb-1",
                    "aria-hidden": "true"
                }, void 0, false, {
                    fileName: "[project]/src/app/layout.tsx",
                    lineNumber: 29,
                    columnNumber: 9
                }, this),
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                    className: "bg-orb bg-orb-2",
                    "aria-hidden": "true"
                }, void 0, false, {
                    fileName: "[project]/src/app/layout.tsx",
                    lineNumber: 30,
                    columnNumber: 9
                }, this),
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$site$2d$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["SiteHeader"], {
                    locale: locale,
                    messages: messages.header
                }, void 0, false, {
                    fileName: "[project]/src/app/layout.tsx",
                    lineNumber: 31,
                    columnNumber: 9
                }, this),
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("main", {
                    children: children
                }, void 0, false, {
                    fileName: "[project]/src/app/layout.tsx",
                    lineNumber: 32,
                    columnNumber: 9
                }, this),
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$site$2d$footer$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["SiteFooter"], {
                    messages: messages.footer
                }, void 0, false, {
                    fileName: "[project]/src/app/layout.tsx",
                    lineNumber: 33,
                    columnNumber: 9
                }, this)
            ]
        }, void 0, true, {
            fileName: "[project]/src/app/layout.tsx",
            lineNumber: 28,
            columnNumber: 7
        }, this)
    }, void 0, false, {
        fileName: "[project]/src/app/layout.tsx",
        lineNumber: 27,
        columnNumber: 5
    }, this);
}
}),
];

//# sourceMappingURL=src_aac77ae7._.js.map